ユーザー情報(ログインに必要な情報や権限など )を保存する、アカウントテーブルの Model 作成
bob-g12/dayrepo-for-transportation pull request #10
Opened 2024-02-13 16:21 UTC by bob-g12

#アカウントテーブル
## 各項目の意図
### id
- 自動採番であることからフィールドはAutoFieldを選択
- PK
- 基本的に変更を受け付けない
- ユーザー数が多くないことが想定されるため、暫定で最大文字数は６桁
- 未入力およびデータが無いことを許容しない

### last_name/first_ name
- 文字列のデータを扱うのでフィールドはCharFieldを選択
- 最大文字数は25桁、未入力およびデータが無いことを許容しない

### password
- Q: CharFieldにしてるけどSlugFieldのほうがいいのかな？ -> https://github.com/bob-g12/dayrepo-for-transportation/pull/10#discussion_r1493734726
- 最大文字数は20桁(現時点でこの数字に意味はない)
- 未入力およびデータが無いことを許容しない

### is_administrator/is_approval
- True or False のデータを扱うので BooleanField を選択
- デフォルトではFalseとし、未入力およびデータが無いことを許容しない

### create_at
- 日時のデータを扱うのでフィールドはDateTimeFieldを選択
- データを新規作成する際に日時を自動登録

### update_at
日時のデータを扱うのでフィールドはDateTimeFieldを選択
- データを更新する際に日時を自動登録

## テーブルの定義
    type = table
    name = accounts
tbl_name = accounts
rootpage = 37
     sql = CREATE TABLE "accounts" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "last_name" varchar(25) NOT NULL, "first_name" varchar(25) NOT NULL, "is_administrator" bool NOT NULL, "is_approval" bool NOT NULL, "create_at" datetime NOT NULL, "update_at" datetime NOT NULL, "password" varchar(20) NOT NULL)

2024-02-14 02:24 UTC, ittyi requested changes

2024-02-14 02:24 UTC, ittyi commented on models.py
> +    #user_id = models.Field('googleユーザーID')
```suggestion
```
不要なコードは消しましょう〜
これ結構便利なのですが、「Commit Suggestion」から「Commit changes」で変更をコミットできますのでよければ！※行った場合、再度新しく編集するときはローカルでgit pulが必要です
<img width="813" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/40ab7c14-b42f-4327-9385-c1323cdc062c">
https://devblog.thebase.in/entry/2018/12/02/130657

2024-02-14 02:24 UTC, ittyi commented on models.py
> +    id = models.AutoField('アカウントID',primary_key=True,editable=False,max_length=6,blank=False, null=False)
このアカウントIDという文字列は、verbose_name="アカウントID"ですかね？ 他の項目も含めて、必要でしたら修正お願いしますmm

2024-02-14 12:40 UTC, bob-g12 commented
#車両テーブル
## 各項目の意図
### id
- 自動採番であることからフィールドはAutoFieldを選択
- PK
- 基本的に変更を受け付けない
- ユーザー数が多くないことが想定されるため、暫定で最大文字数は６桁
- 未入力およびデータが無いことを許容しない

### vehicle_number
- 文字列のデータを扱うのでフィールドはCharFieldを選択
- 最大文字数は15桁、未入力およびデータが無いことを許容しない

### now_mileage
- 最大文字数は25桁(現時点でこの数字に意味はない)
- 未入力およびデータが無いことを許容しない

2024-02-14 13:17 UTC, bob-g12 commented
# チェックリストテーブル
## 各項目の意図
### snippet_id
- 外部キーであることからフィールドはForeignKeyを選択
- Snippetテーブルから外部キーを取得
- オブジェクトを削除した場合、元データも削除
- データが無いことを許容しない

### その他項目
- True or False のデータを扱うので BooleanField を選択
- デフォルトではFalseとする。
- 基本的にデータが無いことを許容せず、未入力は許容するが、
現状前日と本日の異常点検のみ、未入力を許容しない

2024-02-15 02:41 UTC, ittyi requested changes
コメントしました！
また、結局アカウントテーブルだけのPRにしたのかな？

その場合、車両とchecklistのコメントはどこかにコピペ保存して、このPRからは消してほしいです

2024-02-15 02:41 UTC, ittyi commented on dayrepo/snippets/models.py
> +    id = models.AutoField(verbose_name='アカウントID',primary_key=True,editable=False,blank=False, null=False)
[nits]
ここ、アカウントテーブル内では外部キーじゃないのでidでいいと思う！

あと、個人的には周りに合わせて小文字で id 派です

2024-02-15 02:41 UTC, ittyi commented on dayrepo/snippets/admin.py
> +admin.site.register(Account)
Q
こちらは何のために入れたコードでしょうか？後学のための質問ですmm

2024-02-17 04:04 UTC, bob-g12 commented
> #アカウントテーブル
> 
> ## 各項目の意図
> ### ID
> * 自動採番であることからフィールドはAutoFieldを選択
> * PK
> * 基本的に変更を受け付けない
> * ユーザー数が多くないことが想定されるため、暫定で最大文字数は６桁
> * 未入力およびデータが無いことを許可しない
> 
> ### 姓/名
> * 文字列のデータを扱うのでフィールドはCharFieldを選択
> * 最大文字数は25桁、未入力およびデータが無いことを認めない
> 
> ### パスワード
> * Q: CharFieldにしてるけどSlugFieldのほうがいいのかな？
> * 最大文字数は20桁(気づいてこの数字に意味はない)
> * 未入力およびデータが無いことを許可しない
> 
> ### is_administrator/is_approval
> * True または False のデータを扱うので BooleanField を選択
> * もちろんではFalseとし、未入力およびデータが無いことを認めない
> 
> ### 作成時
> * 日付のデータを扱うフィールドはDateTimeFieldを選択
> * データを新規作成する際に日付を自動登録
> 
> ### update_at
> 日付のデータを扱うフィールドはDateTimeFieldを選択
> 
> * データを更新する際に日付を自動登録

Django_adminページにてテーブルの作成及びバリデーションの確認が完了しました。
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/cc1d502d-02a1-404c-889c-2c4009c44b4b)
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/985f3c10-ee25-48f8-8dce-814265294193)

2024-02-18 10:23 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +    id = models.AutoField(verbose_name='アカウントID',primary_key=True,editable=False,blank=False, null=False)
verbose_nameの話してる？
アカウントの項目のidだからアカウントのidの表記だけでわかるとは思うけど、
悪影響はないし、親切さもあってアカウントidの表記がいいと思ってる。

2024-02-18 10:25 UTC, bob-g12 commented on dayrepo/snippets/admin.py
> +admin.site.register(Account)
これ入れるとDjango_adminのサイト上でテーブルが確認＆編集できるようになりましま

2024-02-18 11:06 UTC, ittyi requested changes
コメントしました〜

2024-02-18 11:06 UTC, ittyi commented on dayrepo/snippets/models.py
> +    is_today_trouble = models.BooleanField(verbose_name='本日の異常',default=False,blank=False, null=False)
[nits]
とっても細かいですが、以下のようにスペースがあったりなかったりするので、フォーマットをするといいです。
VScodeの編集中のファイル内で右クリックをし、「ドキュメントのフォーマット」といったボタンを押す、もしくはファイルの保存時に自動でやってくれるように設定する。などの手段が取れます。

<img width="668" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/bfbc2a12-2d70-4da0-8d6d-a25aeeae2560">

2024-02-18 11:06 UTC, ittyi commented on dayrepo/snippets/models.py
> +        db_table = 'car'
[nits]
これも細かいですが、accountテーブルの方がDB上では  Accounts と複数形になっているのに対し、こちらは単数形にしているのは何か意図がありますか？
特になければ、class名の定義はそのままでテーブル名は複数形などに統一するといいのかなとは思いました。
https://ejje.weblio.jp/content/cars

checklistも同様です。
https://ejje.weblio.jp/content/checklist

2024-02-18 11:17 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +    id = models.AutoField(verbose_name='アカウントID',primary_key=True,editable=False,blank=False, null=False)
異論はない(イケオジボイス)

2024-02-18 11:17 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +    id = models.AutoField(verbose_name='アカウントID',primary_key=True,editable=False,blank=False, null=False)
異論はありません

2024-02-18 11:40 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +    is_today_trouble = models.BooleanField(verbose_name='本日の異常',default=False,blank=False, null=False)
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/9726da36-fd5f-4d4d-9aca-4ea6d27a25ab)
どれのこと？

2024-02-18 12:00 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +    is_today_trouble = models.BooleanField(verbose_name='本日の異常',default=False,blank=False, null=False)
できました

2024-02-18 13:26 UTC, ittyi commented on dayrepo/snippets/models.py
> +    id = models.AutoField(verbose_name='アカウントID',primary_key=True,editable=False,blank=False, null=False)
verbose_nameの話だよ〜
小文字についてはどうじゃ？

2024-02-18 13:39 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +    id = models.AutoField(verbose_name='アカウントID',primary_key=True,editable=False,blank=False, null=False)
小文字は特になんとも
小文字で解決でよさそうならそうしとく

2024-02-18 15:26 UTC, bob-g12 commented
定義一覧
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/8379cd91-0ab7-46ee-ae35-f2f9e342e205)

2024-02-20 01:33 UTC, ittyi approved these changes
一旦マージしてしまいましょう〜

2024-02-20 01:33 UTC, merged