add: 新しいDBテーブル snippetsの雛形作成
bob-g12/dayrepo-for-transportation pull request #14
Opened 2024-02-17 14:51 UTC by bob-g12

後ほど追記

2024-02-20 17:06 UTC, ittyi commented on dayrepo/snippets/models.py
> +        verbose_name="日報ID", primary_key=True, editable=False, blank=False, null=False, default=False
editable=False について、前回と同様の理由で今回は trueにしたいです！
https://github.com/bob-g12/dayrepo-for-transportation/pull/10#discussion_r1493732559

2024-02-21 05:30 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +        verbose_name="事故/遅延等異常_処置", default=False, blank=True, null=False
そこはいまだに迷っていて、何かあった場合はTrueというのは確実なんだけど、
記入漏れ状態が必要なのかどうか、無記入＝Falseのほうが操作が楽になるけど、記入しなきゃいけなかった場合の漏れに気が付けない、
ただ、事故などの異常に対するこの項目は、実際のところnoしか書かない、何かあっても口頭や他のところでやり取りする、たぶんあまり問題の痕跡を残したくないため…
世間一般的な視点を含めたアプリとしてならばデータは、記入のTrue/falseと未記入のnull(受け付けない)の三択がいいけど、
実用性を考えるならデータは、記入のTrueと未記入のfalseの二択かなって

2024-02-21 05:32 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +    oil = models.FloatField(verbose_name="オイル", max_length=4, blank=True, null=True)
給油は少数の第一位までは必要ですね

2024-02-21 05:34 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +    oil = models.FloatField(verbose_name="オイル", max_length=4, blank=True, null=True)
オイルはめったにないのでよくわからないけど、同じℓ単位の記録だから欲しいかな

2024-02-21 05:37 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +        verbose_name="天気", max_length=5, blank=False, null=False, default=False
一度エラー食らってデフォルト追加求められた気したけど、改めて消してmakeとmigrateしたら何事もなく通ったので修正しときます。

2024-02-21 05:40 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +        verbose_name="休憩地点", blank=False, null=False, max_length=10
まあ大きくていいなら大きいに越したことないですね。修正します

2024-02-21 16:11 UTC, bob-g12 commented
#業務トラブルテーブル
## 各項目の意図
###snippet_id
- FK
- このデータが削除された場合何もしない
- 未入力およびデータが無いことを許容しない
### trouble_situation/trouble_cause/trouble_support
- 文字を扱うのでCharFieldを選択
- 最大文字数は100桁、
- 未入力データが無いことを許容しない

![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/045b909d-4526-4e38-a0d6-5b8585ddd6da)

2024-02-22 16:22 UTC, ittyi requested changes
コメントしました！

2024-02-22 16:22 UTC, ittyi commented on dayrepo/snippets/models.py
> +        verbose_name="日報ID",
全部一通り統一しましょう〜
```suggestion
        verbose_name="日報id",
```

2024-02-22 16:22 UTC, ittyi commented on dayrepo/snippets/models.py
> +        verbose_name="アカウントID",
```suggestion
        verbose_name="アカウントid",
```

2024-02-22 16:22 UTC, ittyi commented on dayrepo/snippets/models.py
> +class Duties_trouble(models.Model):
基本的に、スネークケースとキャメルケースが混ざってしまうのは命名として良くないです。

また、今回はPythonのclass名はアッパーキャメルケースで統一しましょう〜。コーディング規約とかも作った方がいいかもですね。
```suggestion
class DutiesTrouble(models.Model):
```

suggestionを採用する場合、git pull と migrate し直すのをお忘れなく！

2024-02-22 16:22 UTC, ittyi commented on dayrepo/snippets/models.py
> +        verbose_name="トラブルid",
トラブルidでは 業務トラブルであることが伝わらないので、省略せずに業務トラブルidでいいかと思います。

2024-02-22 16:22 UTC, ittyi commented on dayrepo/snippets/models.py
>      # snippet テーブルがまだ未定義のため、一時コメントアウト
もうこのコメントはいらないかな？
```suggestion
```

2024-02-22 16:22 UTC, ittyi commented on dayrepo/snippets/models.py
> +        on_delete=models.CASCADE,
[Q]
CASCADEにした場合、大元の日報が削除されると紐づくレコードも削除されますが、これは意図通りですか？

2024-02-22 16:22 UTC, ittyi commented on dayrepo/snippets/models.py
> +        default=False,
idが入るカラムでdefault=Falseはおかしいかなと！
```suggestion
```

2024-02-22 16:22 UTC, ittyi commented on dayrepo/snippets/models.py
>          blank=True,
以下全ての項目で言えますが、Boolean で空文字は存在しないはずなので、特筆すべき理由がなければ全て デフォルト設定の blank=False でいいかなと思います。

2024-02-22 16:22 UTC, ittyi commented on docs/command.md
> +git checkout -b feature/"目的ののブランチ"
のの？笑
```suggestion
git checkout -b feature/"目的のブランチ"
```

全然関係ないけど、せっかくならgit pull, git status, git logもあるといいかも？

2024-02-22 16:22 UTC, ittyi commented on docs/command.md
> +##### テーブル表示
これ上にも同じやつあるの気になります！

2024-02-22 16:58 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +        verbose_name="トラブルid",
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/a9763e64-beb7-4ebe-b273-2eaca8ee992f)

2024-02-22 17:07 UTC, bob-g12 commented on docs/command.md
> +##### テーブル表示
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/90a8fafd-de89-434b-9d02-796c5c8cf183)

2024-02-22 17:17 UTC, bob-g12 commented on dayrepo/snippets/models.py
>          blank=True,
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/5a3e4cec-52c6-4b53-abd8-6d57cb6bf110)

2024-02-23 04:53 UTC, ittyi requested changes
最後！

2024-02-23 04:53 UTC, ittyi commented on dayrepo/snippets/models.py
> +        'Dutiestrouble',
くっそ細かいけど。migrateもワンチャンうまくできてない可能性があるから、コマンドの打ち直しもよろしく
```suggestion
        'DutiesTrouble', 
```

2024-02-23 04:53 UTC, ittyi commented on dayrepo/snippets/models.py
> +    duties_id = models.ForeignKey(
ここも省略しなくていいと思う〜
```suggestion
    duties_trouble_id = models.ForeignKey(
```

2024-02-23 04:53 UTC, ittyi commented on dayrepo/snippets/models.py
> +class Snippet(models.Model):
[Q]
あと、snippets テーブルに car_id の外部キーは持たせなくていいんだっけ？
※仕様書みろ案件(だけどあえて聞いて終わらす←

2024-02-23 04:53 UTC, ittyi commented on docs/command.md
> +git  branch
上でまだコメントがあったのでついでに 笑
```suggestion
git branch
```

2024-02-23 07:55 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +class Snippet(models.Model):
変更しました
[dayrepo/snippets/models.py](https://github.com/bob-g12/dayrepo-for-transportation/pull/14/commits/7f1074004bd67fa8a8fea3e8cb92ff455f441c27#diff-e25aeddee8d3cc0744b198a1b399187811c702d5a02023aa8f3c25d82979bb39R137-R143)

2024-02-23 08:03 UTC, ittyi approved these changes
LGTM！

2024-02-23 08:04 UTC, merged