日報一覧ページの作成(簡易)
bob-g12/dayrepo-for-transportation pull request #25
Opened 2024-02-24 07:46 UTC by bob-g12

##  PRの意図
暫定的に一覧画面の作成を行います。
簡易的にする理由は、アプリ全体の動作として完成することを優先するため
主にデザインやテーブル間のデータの共有などは別のPRで進める。
現時点での日報を表示する画面です
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/5eb98f49-73db-4f05-806c-50cd55825f8e)
※adminにDutiesTroubleの追加、snippetテーブルにfree_spaceを追加

2024-02-29 17:02 UTC, ittyi requested changes
コメントしました〜

2024-02-29 17:02 UTC, ittyi commented on dayrepo/snippets/views.py
> +class Snippet_listView(View):
```suggestion
class SnippetListView(View):
```

2024-02-29 17:04 UTC, bob-g12 commented on dayrepo/snippets/admin.py
> +admin.site.register(DutiesTrouble)
そうっすね

2024-02-29 17:06 UTC, bob-g12 commented on dayrepo/snippets/models.py
> +    free_space = models.CharField(
備考欄はER図にあったのに抜けてた部分ですね

2024-02-29 17:07 UTC, bob-g12 commented on dayrepo/snippets/templates/snippet_list.html
> +        <p class="car_number">{{ post.free_space }}</p>
変ですね

2024-03-01 09:09 UTC, bob-g12 commented on dayrepo/snippets/templates/snippet_list.html
> +        <p class="car_number">{{ post.free_space }}</p>
対応しました。

2024-03-01 09:20 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +class Snippet_listView(View):
ここ、下の変数そのままなの怖い
公明の罠かな？

2024-03-01 17:29 UTC, ittyi commented on dayrepo/snippets/admin.py
> +admin.site.register(DutiesTrouble)
PRのタイトルと説明にある意図からは明らかに離れてるから、こういうのはこんな感じでこめんとするといいよ。

2024-03-01 17:30 UTC, ittyi commented on dayrepo/snippets/admin.py
> +admin.site.register(DutiesTrouble)
前回PRのやり忘れ

2024-03-01 17:32 UTC, ittyi commented on dayrepo/snippets/models.py
> +    free_space = models.CharField(
https://github.com/bob-g12/dayrepo-for-transportation/pull/25#discussion_r1509309051
上記と同じく、記載したほうが親切やで！

2024-03-01 17:38 UTC, ittyi approved these changes
最後！

2024-03-01 17:38 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("snippet_list/", views.snippet_list,name="snippet_list"),
前回見逃しすまん、APIのパスは今回は念の為ハイフン(-)で区切ってほしい！

https://ramble.impl.co.jp/2886/#:~:text=%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E5%BD%B9%E5%89%B2-,%E3%82%A2%E3%83%B3%E3%83%80%E3%83%BC%E3%82%B9%E3%82%B3%E3%82%A2%E3%81%AF%E5%A5%BD%E3%81%BE%E3%81%97%E3%81%8F%E3%81%AA%E3%81%84,%E3%81%93%E3%81%A8%E3%81%8C%E3%81%82%E3%82%8B%E3%81%9F%E3%82%81%E3%81%A7%E3%81%99%E3%80%82
> REST API では、記号を使ったり URL を記述するときには、ハイフンを使うことが推奨されます。
> 
> これは、ハイフンは URL のエンコーディングによって改変されず、アンダースコアは改変されることがあるためです。
> 
> 例として、アンダースコアを使用した URL をエンコードした場合にどうなるのか見てみます。
> 以下のURLをご覧ください。
> 
> ・https://impl.com/api/items/item_id_1
> 
> これをエンコードすると、次のようになります。
> 
> ・https://impl.com/api/items/item%5Fid%5F1

このように、アンダースコアはURLエンコーディングによって変更されることがあるため、REST API ではハイフンを使うことが推奨されます。

2024-03-01 17:38 UTC, ittyi commented on dayrepo/snippets/views.py
> +        # 記録してある投稿の全データを投稿時間を元にソートして表示
@bob-g12 
マイナスをつけたのはあえて？

2024-03-01 17:38 UTC, ittyi commented on dayrepo/snippets/views.py
> +
この改行なんだろう？
フォーマットの影響？
```suggestion
```

2024-03-01 17:41 UTC, ittyi requested changes
まちがえてアプロブしてもーた

2024-03-02 04:08 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        # 記録してある投稿の全データを投稿時間を元にソートして表示
これで最新が上に来るやろ？
その方が便利

2024-03-02 04:23 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("snippet_list/", views.snippet_list,name="snippet_list"),
対応しました。
[dayrepo/snippets/urls.py](https://github.com/bob-g12/dayrepo-for-transportation/pull/25/files#diff-38f6ffac2038ee8b1ce74ecc47b87d9bcdcb7b670945d967cd66145f9c46e89c)

2024-03-02 06:40 UTC, ittyi approved these changes
LGTM〜

2024-03-02 06:40 UTC, merged