日報投稿画面にて工程フォームの追加機能(ボタン)の実装
bob-g12/dayrepo-for-transportation pull request #34
Opened 2024-03-03 12:54 UTC by bob-g12

後ほど記述

2024-03-06 14:27 UTC, bob-g12 commented
フォームを追加することに成功しました。
デバックの産物としてアラートを残しておきました。
なお、現在最後に追加した入力のみになってしまったため、現在はそちらの修正を図っています。
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/914f13b6-5e35-48d6-b4e0-1bc6afadada2)
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/161e74f9-18f6-47d8-a042-81e05e941d57)

2024-03-10 03:54 UTC, bob-g12 commented
工程フォームの追加機能が主ではあったが、他のテーブルにてFKの取得や同一名のフォーム入力値の仕分けもこちらのPRで追加

2024-03-10 06:59 UTC, ittyi approved these changes
コメントしました〜

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +var i = 1 ;
```suggestion
let i = 1 ;
```

現代のJavaScript では、基本的に var で変数を宣言することは非推奨です。
なぜ非推奨なのか？の背景は重要なので、以下の参考記事に目を通しておいてくださいmm 
FYI
[JavaScriptでvarが非推奨な理由を整理してみた](https://qiita.com/ist-t-s/items/49ed558bd837452353b8)
[varはもう使わない](https://typescriptbook.jp/reference/values-types-variables/vars-problems)

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  var content_area = document.getElementById("form_area");
```suggestion
  let content_area = document.getElementById("form_area");
```
これも上記と同じ理由です。
また、基本的には const で宣言する。再代入したくなったら let に変える。という意識で実装するといいと言われています。今回はこの下で変数に変更を加えているため、たぶん let っぽいです。
https://qiita.com/kerupani129/items/c56ae227b8ff6f026884
> プログラミング全般において、変更可能な (ミュータブルな) 変数よりも変更不可な (イミュータブルな) 変数の方が望ましいです。可読性・保守性の向上、バグ削減などのメリットがあります。

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  var clone_element = content_area.cloneNode(true);
```suggestion
  let clone_element = content_area.cloneNode(true);
```

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +function addForm() {
[IMO]
```suggestion
const addForm = () => {
```

必須ではないのですが、今回の関数名 addForm はかなり抽象度が高く命名被りをする可能性があるため、このような記載にしたいです。
基本的な理由は変数と同じです。念の為、修正後動作確認もお願いします。
参考記事は以下
https://jsprimer.net/basic/function-declaration/#function-overwrite

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/templates/snippet_post.html
>          <h1>日報基本情報入力</h1>
```suggestion
        <h2>日報基本情報入力</h2>
```

h1タグは、そのタグの意味合いとして([セマンティックなどと言ったりします](https://catnose.me/learning/tags/%E3%82%BB%E3%83%9E%E3%83%B3%E3%83%86%E3%82%A3%E3%83%83%E3%82%AFHTML) )1ページに一つに抑えられるのが理想です。
参考記事
https://www.willgate.co.jp/promonista/h1/

今回のこの見出しはページの説明ではなくフォームの説明なので、 h2 で十分だと思います。

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/templates/snippet_post.html
>          <h1>異常報告入力</h1>
```suggestion
        <h2>異常報告入力</h2>
```
上記と同じ理由

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/templates/snippet_post.html
> +        <h1>工程入力</h1>
```suggestion
        <h2>工程入力</h2>
```
上記と同じ理由

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/templates/snippet_post.html
> +        <script src="{% static 'js/process_add.js' %}"></script>
[IMO]
基本的に、 script タグは一番下に記載するといいと言われています。
https://tcd-theme.com/2022/01/how-to-run-javascript.html#:~:text=HTML%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%ABscript%E3%82%BF%E3%82%B0,%E4%B8%AD%E3%81%AB%E7%94%A8%E6%84%8F%E3%81%97%E3%81%BE%E3%81%99%E3%80%82&text=%E3%81%95%E3%82%89%E3%81%AB%E3%80%81%E8%BF%91%E5%B9%B4%E3%81%A7%E3%81%AFbody%E3%81%AE,%E4%B8%BB%E6%B5%81%E3%81%A8%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82

今回のアプリの規模では少しの違いではあると思いますが、知識として知っておいてください。というのと、賛同いただければ以下の {% endblock %} の上あたりに移動をお願いします。

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/views.py
> +from django.http import HttpResponse, QueryDict
```suggestion
from django.http import HttpResponse
```
こちらは結局使用しませんでしたので消しますmm

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/views.py
> +        print(request.POST)
```suggestion
```

不要な print

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/views.py
> +            oil = 0.0
```suggestion
        oil = req.get("oil")
        if oil == "":
            oil = 0.0

```

細かいですが、改行の位置を修正したいですmm

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/views.py
> +        print(form_process_count)
```suggestion
```
不要な print

2024-03-10 06:59 UTC, ittyi commented on dayrepo/snippets/views.py
> +
```suggestion
                snippet_id = snippet,

```
ここも改行位置揃えたいですmm

2024-03-10 07:03 UTC, ittyi requested changes
あ、アプロブしてモータ

2024-03-10 07:20 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        print(request.POST)
見逃してました

2024-03-10 07:35 UTC, bob-g12 commented on dayrepo/snippets/templates/snippet_post.html
> +        <script src="{% static 'js/process_add.js' %}"></script>
賛同し、対応しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/34/commits/f9da77eb9ede99f024515ee39b6f857d2cd3efc3

2024-03-10 07:40 UTC, ittyi requested changes
最後！

2024-03-10 07:40 UTC, ittyi commented on dayrepo/snippets/templates/snippet_post.html
> +<script src="{% static 'js/process_add.js' %}"></script>
```suggestion
    <script src="{% static 'js/process_add.js' %}"></script>
```

2024-03-10 07:48 UTC, ittyi approved these changes
LGTM~
ブランチ名は以降揃えましょう

2024-03-10 07:48 UTC, merged