実装済みのリスト表示や保存機能を checklist の仕様変更に合わせ修正修正
bob-g12/dayrepo-for-transportation pull request #39
Opened 2024-03-11 09:30 UTC by bob-g12

## PR概要
- checklistの扱いのなかで今までの実装に変更を加える必要が出来たため、このPRでは、今までの実装段階でやるべきであった実装を主にchecklist絡みを中心に行う
### やること
#### テーブルカラムの推移や追加、それに伴うformやviewの変更
- snippetテーブルから車両、アカウントのFKと稼働日のカラムを削除し、checklist_idのFKを新たに追加
- checklistからsnippet_idを削除し、車両とアカウントのFKと稼働日のカラムを追加
- forms.pyにてモデルと同様に入力フォームを変更し、FK対象の選択肢に別のメッセージを表示する処理の対象を変更、また、snippetテーブルのchecklist_idのFKで必要のため増設
- views.pyにてモデル同様に保存対象を一部変更 and 追加
#### 一覧画面にチェックリストの表示
- viewでlist表示の際に与えるdict値にチェックリストデータを追加
- 与えられたデータをhtmlにて表示
#### checklistのみのデータを選択肢やリストで表示を分ける
- リスト表示画面で、checklistのみ、snippet提出済みで表示を分ける
- snippetでchecklist選択時、他のsnippetで選択されたchecklistを表示しない
### 今後に対応すること
※画面推移も予定と変わったが、そもそもlistページの推移なども未設定なのでこことは別で設定

2024-03-13 15:22 UTC, ittyi requested changes
コメントしました〜！
稼働日以外は全部小さいことだけ！さすがです！

2024-03-15 11:48 UTC, bob-g12 commented on dayrepo/snippets/forms.py
> +        empty_label="点検データを選択してください",
その方が親切ですね

2024-03-15 12:11 UTC, bob-g12 commented on dayrepo/snippets/templates/snippet_list.html
>      {% for post in posts %}
？

2024-03-15 12:30 UTC, ittyi commented on dayrepo/snippets/templates/snippet_list.html
>      {% for post in posts %}
@bob-g12
forで囲った中身は、div も p タグも全部 posts の数分作成されるが、今回divタグはいらないよね？

仮に必要なのであれば、postというクラス名がたくさんできるのは抽象度が高い命名なのでよろしくない

2024-03-15 12:43 UTC, bob-g12 commented on dayrepo/snippets/templates/snippet_list.html
>      {% for post in posts %}
これでいい？
https://github.com/bob-g12/dayrepo-for-transportation/pull/39/commits/5966e311a837677e3066804f7b41413675e2de7a

2024-03-15 12:46 UTC, ittyi commented on dayrepo/snippets/templates/snippet_list.html
>      {% for post in posts %}
あれ、divは消しちゃうの？
あと、その下の提出済みに同じ状態がもういっこあるヨ

2024-03-15 13:04 UTC, bob-g12 commented on dayrepo/snippets/templates/snippet_list.html
>      {% for post in posts %}
下に合わすか…
デザインの時使いそうだし

2024-03-15 13:19 UTC, ittyi commented on dayrepo/snippets/templates/snippet_list.html
>      {% for post in posts %}
いや、下のほうはむしろ1番最初の指摘が直ってないね。

https://github.com/bob-g12/dayrepo-for-transportation/pull/39#discussion_r1526220651

2024-03-15 14:24 UTC, bob-g12 commented on dayrepo/snippets/templates/snippet_list.html
>      {% for post in posts %}
じゃあ消しとく
デザインで必要になったらまた足す
https://github.com/bob-g12/dayrepo-for-transportation/pull/39/commits/b6585d85e107385751700aa0d527728c1a364ed9

2024-03-15 15:52 UTC, ittyi approved these changes
LGTM。

2024-03-15 15:55 UTC, merged