Gokki branch
bob-g12/dayrepo-for-transportation pull request #5
Opened 2024-02-09 07:42 UTC by bob-g12

ER図を作成しました。

2024-02-09 07:48 UTC, bob-g12 commented
ER図画像
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/7ce949a7-a723-4cdd-9952-c20b7f51dfcb)

2024-02-10 03:43 UTC, bob-g12 commented
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/c4f44f73-837d-4c1a-8600-6d5e6a00ebbc)
エンティティの定義

2024-02-10 07:06 UTC, bob-g12 commented
ER図拡大画像
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/ba1de143-3189-4e3b-a413-d96a6fcce239)

2024-02-10 15:35 UTC, ittyi requested changes
@bob-g12 
コメントしました！

ER図はエンティティの定義によってよんどうするので一旦レビューしていません。
※そもそもエンティティの定義とはファイルを分けてくれると嬉しい！

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="226" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;googleアカウント(google_account)&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fo
[must]
アカウントにPK(主キー)がない気がする！
これだと万が一同じ名前で同じパスワードのユーザーができてしまったら特定レコードを取得できなくなってしまう。

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="244" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;名&lt;br&gt;(first name)&lt;br&gt;&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=defa
[nits]
last_name, first nameって英語使ってるのいいね！
first nameの方にもアンダーバーを入れて表記を揃えるのと、この二つを利用すればいいので、full_nameはいらないと思う。

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="20xpJOXveIqqjsol-HEC-1" value="&lt;div style=&quot;&quot;&gt;車両番号&lt;/div&gt;&lt;div style=&quot;&quot;&gt;走行距離&lt;/div&gt;&lt;div style=&quot;&quot;&gt;&lt;br&gt;&lt;/div
[Q]
車両番号って、ひらがなから始まらなかったっけ？
https://www.hanamaru870.net/column/%E8%BB%8A%E4%B8%A1%E7%95%AA%E5%8F%B7%E3%81%A3%E3%81%A6%E4%BD%95%EF%BC%9F%E8%BB%8A%E4%BD%93%E7%95%AA%E5%8F%B7%E3%82%84%E8%BB%8A%E5%8F%B0%E7%95%AA%E5%8F%B7%E3%81%A8%E4%BD%95%E3%81%8C%E9%81%95%E3%81%86/#:~:text=%E3%80%8C%E8%BB%8A%E4%B8%A1%E7%95%AA%E5%8F%B7%E3%80%8D%E3%81%A8%E3%81%AF%E3%83%8A%E3%83%B3%E3%83%90%E3%83%BC,%E3%81%8C%E7%99%BB%E9%8C%B2%E3%83%BB%E7%AE%A1%E7%90%86%E3%81%97%E3%81%BE%E3%81%99%E3%80%82

あと、車両番号は Vehicle number っぽい。
https://www.linguee.jp/%E8%8B%B1%E8%AA%9E-%E6%97%A5%E6%9C%AC%E8%AA%9E/%E7%BF%BB%E8%A8%B3/vehicle+number.html

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="267" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;u&gt;社員の名前&lt;br&gt;(name)&lt;/u&gt;&lt;br&gt;&lt;/font&gt;&lt;/span&gt
[IMO]
ここの社員の名前はfullnameじゃないほうがいいと思う。
Slackでも言ったけど、空白の処理を追加したりしないといけなくなる。それならこっちも last_name, first_nameを持たせて、Excel にはくときもそれを流用したほうがいいかも。

というより、そもそも名前を持たせるんじゃなくてアカウントの主キーを持たせてあげたほうがいいかな。

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="275" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;走行距離&lt;br&gt;&lt;/font&gt;&lt;/span&gt;&lt;span style=&quot;color: rgb(0,
[Q]
この走行距離は、基本的に始メーターと終メーターを計算すれば出てくるものだと思うけど、わざわざデータとして保存しておく必要はあるかな？
編集したりすることを考えると、始メーターと終メーターを編集したりしたら毎回ここも計算し直してDBに保存し直すことになりそうなような？

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="265" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:連携データ　(snippet)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFamily=
[Q]
日報 連携データ(snippet)
と
日報 入力データ(snippet)
と
日報 加算データ(snippet)
と
日報 第二データ(snippet)
？
っていう似た名前だけど英名が同じテーブルがある気がするけど、これらは全部別物？

あととりあえず、第二データはなしな気がするけど、一応命名理由があれば伺いたい(それ以外に表現仕様がないという意見ならわからなくもない

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="299" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:加算データ　&lt;/span&gt;&lt;span style=&quot;font-size: 6px;&quot;&gt;(snippet)&lt;/span&gt;" style="rounded=0;whit
[Q]
火山データと第二データとの違いは？

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="287" value="&lt;font style=&quot;font-size: 11px;&quot; color=&quot;#000000&quot;&gt;&lt;u&gt;日付&lt;br&gt;(date)&lt;/u&gt;&lt;br&gt;&lt;/font&gt;" style="rounded=0;whiteSp
この「日付」はなんの日付かを明示できそう。抽象度は下げられるだけ下げるほうがいいとは思う
※投稿日など

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="365" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報(第二データ)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFamily=Helvetica
第二データが2つある....?

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="366" value="&lt;font style=&quot;&quot; color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;タイヤの損傷(空気圧/摩耗/亀裂/損傷)&lt;/span&gt;&lt;br&gt;&lt;span sty
ここら辺のチェック項目系は、全て true/false の boolean でいいと思う

2024-02-10 15:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="445" value="&lt;span style=&quot;color: rgb(0, 0, 0); font-size: 11px;&quot;&gt;本日の異常&lt;/span&gt;&lt;br style=&quot;color: rgb(0, 0, 0);&quot;&gt;&lt;font style=&quot;&qu
本日の異常がtodayはちょっと分かりづらいかも

2024-02-11 02:09 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="226" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;googleアカウント(google_account)&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fo
アカウントのPKには、氏名(姓と名合体させてフルネームのつもり)だったのを、
姓と名それぞれをPKにして対応しましまｂ
画像は更新済み

2024-02-11 02:13 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="244" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;名&lt;br&gt;(first name)&lt;br&gt;&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=defa
上と同じかな？
氏名(full_mane)なくして対応しやした

2024-02-11 02:17 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="246" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;承認&lt;br&gt;(approval)&lt;br&gt;&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=defau
チェック項目含め、二択項目も同様にtrue/falseで対応すべきかな？
nullを許容する項目も中にはあるからその場合true/false/nullで対応させるか。

2024-02-11 02:28 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="242" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;google&lt;br&gt;アカウント&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFami
この場合、Googleアカウントを認識するためのPKが入力されるのが正しいのかな？
null判定だと紐づけされてないアカウントになるもんなぁ
GoogleアカウントのPKってユーザーIDのほうがいいかな？

2024-02-11 02:49 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="20xpJOXveIqqjsol-HEC-1" value="&lt;div style=&quot;&quot;&gt;車両番号&lt;/div&gt;&lt;div style=&quot;&quot;&gt;走行距離&lt;/div&gt;&lt;div style=&quot;&quot;&gt;&lt;br&gt;&lt;/div
普段車両番号数字しか書いてないから忘れてた。
まぁ全部記載して問題ないやろから修正しといた。

2024-02-11 03:01 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="226" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;googleアカウント(google_account)&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fo
姓と名の組み合わせは同姓同名の人が入社するリスクがあるので、PKにするのは好ましくないです〜

2024-02-11 03:17 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="299" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:加算データ　&lt;/span&gt;&lt;span style=&quot;font-size: 6px;&quot;&gt;(snippet)&lt;/span&gt;" style="rounded=0;whit
加算データを第二データ以降に増やせて
時間や場所はひとつ前or別で入力したデータを引用したりされたりするから。
そこの関係図は必要と思って記載した

2024-02-11 03:19 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="287" value="&lt;font style=&quot;font-size: 11px;&quot; color=&quot;#000000&quot;&gt;&lt;u&gt;日付&lt;br&gt;(date)&lt;/u&gt;&lt;br&gt;&lt;/font&gt;" style="rounded=0;whiteSp
update!

2024-02-11 03:26 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="365" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報(第二データ)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFamily=Helvetica
update

2024-02-11 03:26 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="445" value="&lt;span style=&quot;color: rgb(0, 0, 0); font-size: 11px;&quot;&gt;本日の異常&lt;/span&gt;&lt;br style=&quot;color: rgb(0, 0, 0);&quot;&gt;&lt;font style=&quot;&qu
update

2024-02-11 03:36 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="366" value="&lt;font style=&quot;&quot; color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;タイヤの損傷(空気圧/摩耗/亀裂/損傷)&lt;/span&gt;&lt;br&gt;&lt;span sty
確認不要項目もあるみたいだから
true/false/nullの方がいいのか、
不要であることの選択肢が必要なのか…

2024-02-11 04:34 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="244" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;名&lt;br&gt;(first name)&lt;br&gt;&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=defa
あれ？アンダーバーなくしちゃった？
DBはスペースだめだよ〜

2024-02-11 04:35 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="246" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;承認&lt;br&gt;(approval)&lt;br&gt;&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=defau
nullを許容するかどうかはDBにNOT NULL制約をつけるかつけないかで制御できるから、エンティティ的にはbooleanであることがわかればいいと思う〜

2024-02-11 05:10 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="242" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;google&lt;br&gt;アカウント&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFami
Googleアカウントのほう、Slackでもいったけど単純にRDBに取り込める情報なのかがよくわからないから、一旦保留にしようか。

とりあえず、アカウントにはGoogleアカウントのPKが入るのは合ってるヨ

2024-02-11 06:54 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="299" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:加算データ　&lt;/span&gt;&lt;span style=&quot;font-size: 6px;&quot;&gt;(snippet)&lt;/span&gt;" style="rounded=0;whit
加算データを第2データ以降に増やすってどゆこと？

2024-02-11 06:56 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="366" value="&lt;font style=&quot;&quot; color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;タイヤの損傷(空気圧/摩耗/亀裂/損傷)&lt;/span&gt;&lt;br&gt;&lt;span sty
nullかどうかはnot null制約を使えばいいので、エンティティの段階ではどんなデータが入るのかだけがわかればいいかなと。

2024-02-11 07:55 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="226" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;googleアカウント(google_account)&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fo
なんやかんやIDなったのでセーフ

2024-02-11 07:56 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="244" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;名&lt;br&gt;(first name)&lt;br&gt;&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=defa
アンダーバーに被ってるけど消えてないぞい

2024-02-11 07:58 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="246" value="&lt;font style=&quot;font-size: 6px;&quot;&gt;承認&lt;br&gt;(approval)&lt;br&gt;&lt;/font&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=defau
んじゃこの形でええか

2024-02-11 07:59 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="242" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;google&lt;br&gt;アカウント&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFami
了解

2024-02-11 08:26 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="299" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:加算データ　&lt;/span&gt;&lt;span style=&quot;font-size: 6px;&quot;&gt;(snippet)&lt;/span&gt;" style="rounded=0;whit
この欄のイメージなんだけど、
必要に応じて項目増やせるようにしたいから第二データまで書いた。
時間とかは他のデータと同じでないとおかしいところもあるし、増えるよーだけだとわかりづらいと思って
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/52d02514-871b-4c33-ad83-fccd28b1cd38)

2024-02-11 08:33 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="299" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:加算データ　&lt;/span&gt;&lt;span style=&quot;font-size: 6px;&quot;&gt;(snippet)&lt;/span&gt;" style="rounded=0;whit
あー
この工程1, 2, 3とかに応じて増えていくってことね。
となるとまず、テーブル間の関係性を表すために大本になる日報のpkを持つ必要がある。そうしないとjoinができない。

あと、「第二」だと意味がなさすぎるから、もう少しなんかいいネーミングないかな？
どちらにせよsnippetではないよね🤔

2024-02-11 08:43 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="299" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:加算データ　&lt;/span&gt;&lt;span style=&quot;font-size: 6px;&quot;&gt;(snippet)&lt;/span&gt;" style="rounded=0;whit
変更したのだ

2024-02-11 08:47 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="299" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:加算データ　&lt;/span&gt;&lt;span style=&quot;font-size: 6px;&quot;&gt;(snippet)&lt;/span&gt;" style="rounded=0;whit
画像の二枚目以降すべて同じテーブルで管理とかできないかな？

2024-02-11 08:50 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="267" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;u&gt;社員の名前&lt;br&gt;(name)&lt;/u&gt;&lt;br&gt;&lt;/font&gt;&lt;/span&gt
ここは解決済みかな

2024-02-11 08:51 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="275" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;走行距離&lt;br&gt;&lt;/font&gt;&lt;/span&gt;&lt;span style=&quot;color: rgb(0,
保存しておく必要ないわ
変えとく

2024-02-11 08:51 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="265" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:連携データ　(snippet)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFamily=
ほんとは同じにしたい

2024-02-11 09:14 UTC, bob-g12 commented
後解決してないのが
日報テーブルをどうくくるか
全て一つにくくるか
工程のデータと、チェックデータ、その他の入力データの３つでくくるかしたいんだけど

2024-02-11 10:57 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="267" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;u&gt;社員の名前&lt;br&gt;(name)&lt;/u&gt;&lt;br&gt;&lt;/font&gt;&lt;/span&gt
![Screenshot_20240211-195508](https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/24b3ab15-3260-4a7d-8a17-a0e16172aef9)

この社員のところ！
ここは絶対にアカウントに存在するものしか入らない(外部キー制約)に該当するから、そもそも名前じゃなくてアカウントIDを入れるのがオーソドックスやね。

2024-02-11 11:10 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="265" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:連携データ　(snippet)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFamily=
分けるってことでいいんだっけ？
分ける場合、
・すべての関連テーブルにsnippet_idを持たせてください。→joinするときに必要です
・processという同じテーブルの名前が存在するように思えるので、なにかsnippet_ナントカで一意な名前に変更しましょう。(checklistはそのままでいいです)
第二データという

2024-02-11 11:44 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="299" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:加算データ　&lt;/span&gt;&lt;span style=&quot;font-size: 6px;&quot;&gt;(snippet)&lt;/span&gt;" style="rounded=0;whit
こちらで議論中
https://github.com/bob-g12/dayrepo-for-transportation/pull/5#discussion_r1485572614

基本的に、1つのテーブルでカラムを持ちすぎるのは気になる。不吉な匂いがする。
http://www.flint.jp/blog/?entry=65

あと、第二テーブルは名前以外は分けたのナイスアイデアだと思うんだけど、そこ以外のテーブルが意味のあるデータの集合として分けられているか？は今一度考え直してみてほしい。
例えば、投稿時刻、出発時刻、到着時刻、運転時間、休憩時間、業務時間、拘束時間ってテーブル分ける意味あるかな？
※拘束時間はそもそも計算すれば出せそう？

2024-02-11 13:50 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="299" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:加算データ　&lt;/span&gt;&lt;span style=&quot;font-size: 6px;&quot;&gt;(snippet)&lt;/span&gt;" style="rounded=0;whit
計算で出るものは削除した

2024-02-11 16:17 UTC, ittyi requested changes
コメントしました！
あともう少しかなと思います〜〜

2024-02-11 16:17 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="265" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報:連携データ　(snippet)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFamily=
管理者権限の人間が別の人の投稿を編集することがあるため、日報に最終更新日(updated_at) と 最終更新者(updated_by)のカラムを追加してください。
updated_byには基本的にアカウントIDが入る形で大丈夫です。

2024-02-11 16:17 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="365" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報(第二データ)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFamily=Helvetica
テーブル名の check_list ですが、英語で普通に checklist と記載するようなので、アンダーバーなしで大丈夫です〜

2024-02-12 02:05 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="315" value="&lt;font color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;荷主&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;(c
client はprocessにしかいないっすね

2024-02-12 02:30 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="315" value="&lt;font color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;荷主&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;(c
ホントだ。
むしろprocessの中に2つあるね。これを1つにしよう
![Screenshot_20240212-112933](https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/3c625f81-f808-4414-a1ef-66ac54df6a1a)

2024-02-12 02:36 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="300" value="&lt;span style=&quot;color: rgb(0, 0, 0); font-size: 10px;&quot;&gt;出発時刻&lt;/span&gt;&lt;br style=&quot;color: rgb(0, 0, 0); font-size: 10px;&quot;&gt;&lt;span
業務の全体における出発時刻、地点と到着時刻、地点をsnippetに入力して
processに工程ごとの時刻、地点の入力をするけど、一番最初と最後はsnippetの内容に、
第二工程の出発は一つ目の到着と同じでないといけないから、
必要かなって

2024-02-12 02:49 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="266" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;u&gt;車両番号&lt;br&gt;(car_number)&lt;/u&gt;&lt;br&gt;&lt;/font&gt;&lt;/sp
車両のIDとsnippetの車両番号の削除しましま

2024-02-12 02:51 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="300" value="&lt;span style=&quot;color: rgb(0, 0, 0); font-size: 10px;&quot;&gt;出発時刻&lt;/span&gt;&lt;br style=&quot;color: rgb(0, 0, 0); font-size: 10px;&quot;&gt;&lt;span
ちなみにこれ、実際に入力される時刻情報はsnippetとprocessで意味が違ったりするってことかな？

意味が違うなら命名とデータ例を同じじゃなく変えて残す分には気にならない。意味的に同じデータなのであれば、どっちかだけに統一したい。

2024-02-12 03:18 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="266" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;u&gt;車両番号&lt;br&gt;(car_number)&lt;/u&gt;&lt;br&gt;&lt;/font&gt;&lt;/sp
車両テーブルのほうのidは、car_っていう接頭辞はつけなくて大丈夫！
実際に利用するときに自然とcar.idとかになって既に明示的だから、カラム名としてはidだけでいい。

process_idとaccount_idもidだけで大丈夫。
snippet_idは、外部キーとして使う時だけは接頭辞を付けて、本体のsnippetテーブルはidだけでいきましょう〜

2024-02-12 03:21 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="413" value="&lt;font style=&quot;font-size: 8px;&quot; color=&quot;#000000&quot;&gt;運転以外の&lt;br&gt;業務時間&lt;br&gt;(work_time)&lt;br&gt;&lt;/font&gt;" style="rounded=0;white
practice_timeは練習時間ですなぁ

2024-02-12 03:25 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="366" value="&lt;font style=&quot;&quot; color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;タイヤの損傷(空気圧/摩耗/亀裂/損傷)&lt;/span&gt;&lt;br&gt;&lt;span sty
こちらもよろしく！

2024-02-12 03:27 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="365" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;日報(第二データ)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=default;fontFamily=Helvetica
![Screenshot_20240212-122650](https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/9d3d66d8-d49a-4da9-b77e-ab97d274e8cb)

直ってなさそう！

2024-02-12 03:44 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="266" value="&lt;span style=&quot;font-size: 6px;&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;u&gt;車両番号&lt;br&gt;(car_number)&lt;/u&gt;&lt;br&gt;&lt;/font&gt;&lt;/sp
変更したのだ

2024-02-12 03:45 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="413" value="&lt;font style=&quot;font-size: 8px;&quot; color=&quot;#000000&quot;&gt;運転以外の&lt;br&gt;業務時間&lt;br&gt;(work_time)&lt;br&gt;&lt;/font&gt;" style="rounded=0;white
実務もpracticeっていうんじゃないの？

2024-02-12 03:47 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="315" value="&lt;font color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;荷主&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;(c
工程によって届け先変わる可能性もあるから工程ごとに必要じゃね？

2024-02-12 03:48 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="413" value="&lt;font style=&quot;font-size: 8px;&quot; color=&quot;#000000&quot;&gt;運転以外の&lt;br&gt;業務時間&lt;br&gt;(work_time)&lt;br&gt;&lt;/font&gt;" style="rounded=0;white
いわなさそう！
https://ejje.weblio.jp/content/practice
![Screenshot_20240212-124751](https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/e575c103-3286-4191-8433-d6e929d470a4)

2024-02-12 03:49 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="413" value="&lt;font style=&quot;font-size: 8px;&quot; color=&quot;#000000&quot;&gt;運転以外の&lt;br&gt;業務時間&lt;br&gt;(work_time)&lt;br&gt;&lt;/font&gt;" style="rounded=0;white
![Screenshot_20240212-124859](https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/17362c27-6d9e-41ed-9244-abf333bfdce0)
これとか良さそう〜

2024-02-12 03:50 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="342" value="&lt;span style=&quot;color: rgb(0, 0, 0); font-size: 11px;&quot;&gt;経由地&lt;/span&gt;&lt;br style=&quot;color: rgb(0, 0, 0); font-size: 11px;&quot;&gt;&lt;span
片方だけ直ってないかも？
processの中に2つ経由地がある？🤔

2024-02-12 03:57 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="366" value="&lt;font style=&quot;&quot; color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;タイヤの損傷(空気圧/摩耗/亀裂/損傷)&lt;/span&gt;&lt;br&gt;&lt;span sty
文章読んでもここよくわからん

2024-02-12 04:00 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="366" value="&lt;font style=&quot;&quot; color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;タイヤの損傷(空気圧/摩耗/亀裂/損傷)&lt;/span&gt;&lt;br&gt;&lt;span sty
これらのカラム名、全部is_tire_damageのように変更をお願いします！
![Screenshot_20240212-125901](https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/ca98752e-0467-4673-99fa-4d4f285df498)

2024-02-12 04:06 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="316" value="&lt;font color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;品名&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;(g
運ぶものが物資のこともあるし、商品であることもあるし、
様々だから広い表現の方が適格だと思う

2024-02-12 04:09 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="416" value="&lt;font color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 8px;&quot;&gt;業務時間&lt;br&gt;(total_work)&lt;br&gt;&lt;/span&gt;&lt;/font&gt;" style="roun
いっそwork_timeでよくね？
ってか計算で算出するだけだからデータとして保存する必要ないわ

2024-02-12 04:10 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="413" value="&lt;font style=&quot;font-size: 8px;&quot; color=&quot;#000000&quot;&gt;運転以外の&lt;br&gt;業務時間&lt;br&gt;(work_time)&lt;br&gt;&lt;/font&gt;" style="rounded=0;white
nonつけといた

2024-02-12 04:15 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="316" value="&lt;font color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;品名&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;(g
なるほどね
じゃあ最後に1つだけ確認！
以下参考にあるように、ビジネスシーンではproductが使われることが多いのだけど、今回の品は消費者としての品を表していますか？
また、品"名"なのであればname的な何かはあったほうがより明示的ではあるけど、あえてつけない判断でいいかな？

https://kimini.online/blog/archives/6989
> 「Goods」は、「商品」や「品物」といった意味を持つ単語です。 「Product」は製造・販売側から見た「商品」のことだと前述しましたが、「goods」は消費者側から見た場合の「商品」にあたります。 ですから、消費者視点で「商品」と言いたい場合は、「goods」が使えます。

https://www.zkai.co.jp/ca/post-20121/

2024-02-12 04:16 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="413" value="&lt;font style=&quot;font-size: 8px;&quot; color=&quot;#000000&quot;&gt;運転以外の&lt;br&gt;業務時間&lt;br&gt;(work_time)&lt;br&gt;&lt;/font&gt;" style="rounded=0;white
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/9fd7d5f8-5ea0-4fb0-828f-efa87bff01c9)
実務ともいうっぽい

2024-02-12 04:17 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="315" value="&lt;font color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;荷主&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;(c
あーーー！
これ、工程IDが別なのか。
いま意図を理解した 笑

2つ目のほう、(追加)って書くのわかりづらいのと、どっちもレコードが違うだけで同じテーブルに入るはずなので、テーブルを分けずに

processの下に2つレコードがある形にしてもらってよい？
そっちの記載の仕方のほうが通常かも

2024-02-12 09:57 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="366" value="&lt;font style=&quot;&quot; color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;タイヤの損傷(空気圧/摩耗/亀裂/損傷)&lt;/span&gt;&lt;br&gt;&lt;span sty
サンキュー
あと、ここのIDは snippet_id やね
<img width="570" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/6e84b561-afb6-4c4f-aef8-2dc02c83940d">

2024-02-12 10:01 UTC, bob-g12 commented on docs/draw.dio
> +                <mxCell id="316" value="&lt;font color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;品名&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;(g
届け先が消費者ならグッズ、
販売元ならproductなら
どちらもあり得る話だから多種多様な品を指してグッズでいいと思う

2024-02-12 10:09 UTC, ittyi requested changes
コメントしました〜〜
とりあえずこれが直ったら実装開始しましょう

2024-02-12 10:09 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="_Y6IpQlWOBBqGPff7BAM-1" value="工程" style="rounded=0;whiteSpace=wrap;html=1;shadow=1;strokeColor=#36393d;fontFamily=Helvetica;fontSize=8;startSize=0;fillColor=#cce5ff;fontC
ER図についてだけど、まず工程テーブルの出発時刻、出発地点、到着時刻、到着地点は必ず日報テーブルと一致するとは限らないから、外部キーではない。
<img width="189" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/bd37aafc-a77d-40f9-9e81-6ed0f1f20a5b">

2024-02-12 10:09 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="A7u7MnTUe2F30xsEddGq-1" value="日報ID&lt;br&gt;アカウントID　(FK)&lt;br&gt;車両ID　(FK)&lt;br&gt;氏名　&lt;br&gt;始メーター&lt;br&gt;終メーター&lt;br&gt;運転時間&lt;br&gt;運転以外の業務時間&lt;br&gt;休憩時間&lt;b
氏名はアカウントテーブルにあるからいらない！
あと、日付というあまり意味をなしていない名前が戻ってきちゃってるでよ〜

2024-02-12 10:09 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="VH1wcnDR582eS0Y-1mR9-2" value="アカウントID&lt;br&gt;ユーザーID(FK)&lt;br&gt;氏名&lt;br&gt;姓&lt;br&gt;名&lt;br&gt;パスワード&lt;br&gt;承認&lt;br&gt;管理権限" style="rounded=1;whiteSpace=wrap;htm
この氏名は姓と名で十分かな
<img width="200" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/9808011e-3c63-45be-a345-00abc7f520c9">

2024-02-12 10:09 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="VH1wcnDR582eS0Y-1mR9-2" value="アカウントID&lt;br&gt;ユーザーID(FK)&lt;br&gt;氏名&lt;br&gt;姓&lt;br&gt;名&lt;br&gt;パスワード&lt;br&gt;承認&lt;br&gt;管理権限" style="rounded=1;whiteSpace=wrap;htm
<img width="338" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/fb0d759c-18df-4dbb-931d-a191455fe2f0">

一つのアカウントに対してん日報は複数できる関係にあるから、1対多の線で繋げるべきかな！

2024-02-12 10:39 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="366" value="&lt;font style=&quot;&quot; color=&quot;#000000&quot;&gt;&lt;span style=&quot;font-size: 11px;&quot;&gt;タイヤの損傷(空気圧/摩耗/亀裂/損傷)&lt;/span&gt;&lt;br&gt;&lt;span sty
@bob-g12 
あれ？ここって直った？スクショ直してないだけかな？
<img width="790" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/545380be-f996-441b-8f28-03bed6c89387">

2024-02-12 10:42 UTC, ittyi commented on docs/draw.dio
> +                <mxCell id="VH1wcnDR582eS0Y-1mR9-2" value="アカウントID&lt;br&gt;ユーザーID(FK)&lt;br&gt;氏名&lt;br&gt;姓&lt;br&gt;名&lt;br&gt;パスワード&lt;br&gt;承認&lt;br&gt;管理権限" style="rounded=1;whiteSpace=wrap;htm
1 対 多だから、 アカウント側にも1の印がいると思う〜
<img width="537" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/e7d6ea68-2bbc-495a-84cf-1772757218d2">

<img width="743" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/b594b257-cd67-4ae3-9129-89c0143a27ba">

2024-02-12 10:57 UTC, ittyi approved these changes
LGTM！
91のやりとりと13ものコミットお疲れ様〜〜
<img width="460" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/e19d36a6-13da-4ce2-9a2c-a861bae682b3">

2024-02-12 10:58 UTC, merged