作成したsnippetなどのデータを指定してExcelファイルへ入力
bob-g12/dayrepo-for-transportation pull request #51
Opened 2024-03-18 12:53 UTC by bob-g12

## 概要
- ファイルへ入力するデータを指定する機能を仮設定
- 今回のPRも[前回のPRと同じ](https://github.com/bob-g12/dayrepo-for-transportation/pull/43)本格導入前の仮導入だが、前回のPRで不具合があったためこの機能を別のPRにして対応
## 今回のPRでやったこと
- Excelファイルを実際のもの(日報シート)に変更
- リスト画面にファイル編集のボタンを設置しする。
-- 特定のデータを指定して引数として与えるため --
- viewとurlに、ボタンで渡した引数を受け取る編集
- 受け取ったデータから特定のカラム情報を取得
-- 一番複雑と思われるFK先のデータを数例ほどやってみる --
(時間の入力、FK先情報である氏名の入力、bool型を変換して入力)
## 本導入での工程
### Excelファイルの編集箇所
- Excelの入力するセルを調整(統合など)
### Viewsの変更箇所
- [下記のコメント内容](https://github.com/bob-g12/dayrepo-for-transportation/pull/51#issuecomment-2004480435)以外の項目を所得、入力
- snippetテーブルがFKを取得していないテーブルのデータを取得
-- その他のテーブルはsnippet_idを持っているためそこから取得 --
### 全体的な編集
- その他ファイル作成に伴う微調整
## 参考記事
[Excelファイルの編集とダウンロードの仕方](https://qiita.com/t-iguchi/items/3fa5bb8977a29bcf94cf)
[Content-Dispositionやattachment(ファイルのダウンロードや指定方法)](https://zenn.dev/makotot/scraps/ef696b1c280c96)

2024-03-18 17:08 UTC, bob-g12 commented
着色はわかりやすくするためあえて手動で行ったが、データを入力することはできました。
セルを再構築しないと元の文章を消してしまったり、入力値が偏った表示になってしまうので、編集が必要
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/2aebe575-7b2a-4553-8cdb-3f4d6089cc7e)

2024-03-19 14:04 UTC, ittyi requested changes
コメントしました〜

2024-03-19 14:04 UTC, ittyi commented on dayrepo/snippets/views.py
> +    # listのボタンで選択したSnippetデータを変数で受け取る
クライアントの実装を気にしているコメントはあまり芳しくないんだが、これでいかが？
```suggestion
    # 選択したSnippetデータを変数で受け取る
```

2024-03-19 14:28 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
[Content-Disposition](https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Content-Disposition)はファイルをダウンロードしてローカルに保存するために使用。
attachmentはファイルを指定するために使用
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/7c0d1d6f-4ab4-418a-9883-9e4eb485d13e)
filenameはどのfileに書き込むかを指定するために使用

2024-03-19 14:35 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
つまり、

- ウェブページそのものor一部として選択するか、ダウンロードする３択(Content-Disposition)の中から、

- ダウンロードすることを指定し(attachment)、

- 編集するfileは(filename=)、

- %の後に記載された文字列と同盟のfile(=%s)とします

といった感じかな？
ちなみに最後のfile名は変えると警告が出ます

2024-03-19 14:41 UTC, bob-g12 commented on dayrepo/snippets/templates/snippet_list.html
> +    <button onclick="location.href='{% url 'excel_editing' post.id %}'">出力</button>
ボタンを押した結果GETですね
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/07c7237c-2365-4599-b82c-0995b9fb9267)

2024-03-19 14:45 UTC, bob-g12 commented on dayrepo/snippets/excel_file/snippet.xlsx
一度入力してから編集箇所をなくすと入力されていないfileがダウンロードされることから、後者で間違いないかと(空白を指定したわけではなく未入力なので)
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/fce6dd1c-50e6-45a5-85e8-b1c8daa83f18)

2024-03-19 14:46 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
あ、忘れてました
そこだけ変えても挙動バグるのでこちらで修正します

2024-03-19 15:00 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
影響のある範囲が広い話なのでひとつづつ試しながら調整してみます。
端的にパスは、snippets/excel/int:snippet_id/とパスの指定に記載すればいいですか？
ちなみにここで受け取ってるsnippet_idはsnippetテーブルのpkであるidカラムの値なので一応同一ではないです。

2024-03-19 15:04 UTC, bob-g12 commented on dayrepo/snippets/views.py
>      Excel output from template
英語のままというのは関数excelfile_downloadのエクセルが小文字であることを指していますか？
であれば、どちらにするか悩んでいましたが、大文字でいいと思いなおしたので大文字にします。

2024-03-19 15:06 UTC, bob-g12 commented on dayrepo/snippets/views.py
>      Excel output from template
重複というのはコメントと関数名が同じであるということでいいですか？
であれば、コメントという読ませるための記述で日本語を使用するだけの差で十分意味はあると思います。

2024-03-19 15:13 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    # listのボタンで選択したSnippetデータを変数で受け取る
出来ればもう少し選択に対するヒントが欲しいです。
どこで何をどうしたものかという情報を書いたつもりなので。

2024-03-19 15:23 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
そもそも下の変更に伴って消えるのでそのように対応します

2024-03-19 15:24 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
冗長さは対応できませんでしたがおおよそ取り入れたうえで、こちらで動作出来ましたがどうでしょうか？
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/569f0137-4b7e-4b9f-9e06-97e022d1b641)

2024-03-19 15:35 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
同一というのは何を指していまする？

2024-03-19 15:38 UTC, ittyi commented on dayrepo/snippets/views.py
>      Excel output from template
> excelfile_downloadのエクセルが小文字であることを

いえ、コメントについてしかコメントはしていないです

重複というのは、
Excel output from template(直訳: テンプレートからの Excel 出力)
というコメントと、202行目の日本語による
Exelファイル出力

というコメントがほぼ同じことを指しているので、「どちらか1つでいい」もしくは、英語の方の内容をもっと意味のある内容にするべきかと思いました。

2024-03-19 15:47 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
snippet_idで受け取ってるのはSnipprtテーブルのidカラムでありsnippet_idではない

2024-03-19 15:47 UTC, ittyi commented on dayrepo/snippets/excel_file/snippet.xlsx
ありがとう〜

では、静的ファイルにあたるので、staticフォルダの配下に置くべきかと思います。
また、フォルダ名にfileはいらないかなーとも。なにかつけたいなら exel_template などになるかと思いますが、なくてもいいと思います。

2024-03-19 15:50 UTC, bob-g12 commented on dayrepo/snippets/views.py
>      Excel output from template
英語のままってdefの一番上の```で囲われてるやつね。
これイランから消しとくわ

2024-03-19 15:53 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    # listのボタンで選択したSnippetデータを変数で受け取る
では# listページで選択したSnippetデータを変数で受け取る
でいいかな？

2024-03-19 16:07 UTC, bob-g12 commented on dayrepo/snippets/excel_file/snippet.xlsx
エクセルファイルを移動しました
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/bbdf534d-2a8e-4206-baa5-8c4e33bdc930)

2024-03-19 16:13 UTC, ittyi commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
この%はなんですか？

2024-03-19 16:20 UTC, ittyi commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
https://www.javadrive.jp/python/string/index23.html
> 書式化演算子の % を使った方法はかなり以前に使われていたもので、現在は文字列型の format メソッドを使った方法やフォーマット済み文字列リテラルを利用する方法が主流となっています。

とあるのと、

https://www.javadrive.jp/python/string/index24.html#google_vignette
> 書式化演算子 % を使用するよりもより高機能な書式設定が行えるようになりました。

からの
https://www.javadrive.jp/python/string/index25.html
> 文字列の書式化を行うときに、 format メソッドによる方法をより簡潔に行える方法

とあるので、f文字列を使って書きましょうか。
ファイル名を可変にしないのであれば、そもそも最初から文字列でいいかもです。　

個人的には、アプリのユーザーのことを考えるとダウンロードしたファイル名はいい感じに変わってほしい気はしますが…🤔


また2点目の質問として、日報のことをsnippetというのは一般的ではないのですが、職場では一般的に使われている用語ですか？

2024-03-19 16:21 UTC, ittyi commented on dayrepo/snippets/views.py
> +    # listのボタンで選択したSnippetデータを変数で受け取る
> listページで選択した

の部分が、バックエンド側としては関係がないって話しだねぇ

2024-03-19 16:27 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
そこはこのコメントで言及していないので正直どうでもいい 笑
バックエンドAPIとしては、そこはidが入ればなんでもいいので、editing以外はそんなに違和感ないよ。

逆にその説明だと、snippet_id って命名より pk のほうが良さそうには見えてくるけど🤔

2024-03-19 16:52 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
直接文字列に変えました

2024-03-19 16:52 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
snippetをreportに変えました

2024-03-19 16:53 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/fc18abcd-d2b0-42c8-b430-8ce35700a959)

2024-03-19 16:55 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
先ほどの画像の段階でsnippet_idに変えましたがいかがですか？

2024-03-19 17:12 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    # listのボタンで選択したSnippetデータを変数で受け取る
ではこれでいいかな？
# 引数で受け取った値を変数に代入

2024-03-19 17:59 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
snippet_pkにみえる🤔
まぁそこはしょうみどっちでもいいや。

Exel は全部小文字にきましょう。
以下の理由からです。
https://meetup-jp.toast.com/931
> URIパスは小文字が適している
> URIパスに大文字を使うのは避けましょう。大文字と小文字に基づいて別のリソースとして認識してしまうためです。RFC 3986（URI文法形式）は、URIスキームとホストを除き、大文字と小文字を区別するように規定しています。

https://zenn.dev/manamin0521/articles/4eb070df8dd52b
> 大文字小文字が混在していないURI
>混在はAPIをわかりづらく、間違えやすくするので、基本的には小文字で統一する。
既存のAPIにおいては、大文字が混じると404 NotFoundを返すものも多い(GitHub、Tumblrなど)
> なおHTTPにおいて、URIは「スキーマとホスト名を除いては大文字と小文字は区別される」と仕様に書かれている(RFC7230)

2024-03-19 18:05 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
あと、path 関数の name を Exelにしてしまうと、テンプレート側も変えないといけなくなりませんか？

また、path 関数の name はURLの名称を指すので、そちらは exel だけだと逆にわかりにくいです。テンプレートやリダイレクトで使用することも考慮すると、exel_ downloadに合わせるのがいいかと思います。
参考: https://office54.net/python/django/urls-path-include#section1-3

2024-03-19 18:07 UTC, ittyi commented on dayrepo/snippets/views.py
> +    # listのボタンで選択したSnippetデータを変数で受け取る
Snippet である旨もなくなって、よりコメントの必要性を感じないコードみりゃわかるやん状態にはなってしまったが 笑、とりあえずクライアント依存はなくなったのであとはお好きにどうぞ！笑

2024-03-19 18:09 UTC, ittyi commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
念の為動作確認ってした？

2024-03-20 02:43 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
ファイル名にあたる箇所を映しました

2024-03-20 02:46 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
間違えた、snippet_pkに変えました。
パスは小文字に、パスnameはexel_ downloadでよろしいですか？

2024-03-20 02:54 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/fb66539d-983a-4b0c-8e21-59998a7ddfb1)

2024-03-20 02:57 UTC, ittyi commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
動作確認してなかったら念の為やってみてください〜

その 219 行目のファイル名の書き方がそれで大丈夫なのかを確認したいです。

2024-03-20 02:58 UTC, ittyi commented on dayrepo/snippets/templates/snippet_list.html
> +    <button onclick="location.href='{% url 'excel_editing' post.id %}'">出力</button>
いろいろ調べて、GETでしっくりきたのでこのままでおけですb

2024-03-20 02:59 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("excel_editing/<str:snippet_id>/", views.excelfile_download,name="excel_editing"),
fileいるかな…🤔
まぁいいか
LGTM〜

2024-03-20 03:01 UTC, ittyi commented on dayrepo/snippets/views.py
> +    # listのボタンで選択したSnippetデータを変数で受け取る
コードが確認できず、修正されたのかわからないのでとりま残します〜

2024-03-20 03:01 UTC, ittyi commented on dayrepo/snippets/views.py
>      Excel output from template
コードが確認できず、修正されたのかわからないのでとりま残します〜

2024-03-20 03:02 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    response['Content-Disposition'] = 'attachment; filename=%s' % 'snippet.xlsx'
動作確認もやってます
異常なしです

2024-03-20 03:20 UTC, bob-g12 commented on dayrepo/snippets/views.py
>      Excel output from template
[commit](https://github.com/bob-g12/dayrepo-for-transportation/pull/51/commits/fe24403a67263596c67e7de01b8843375a544a74)

2024-03-20 03:20 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    # listのボタンで選択したSnippetデータを変数で受け取る
[commit](https://github.com/bob-g12/dayrepo-for-transportation/pull/51/commits/fe24403a67263596c67e7de01b8843375a544a74)

2024-03-20 03:23 UTC, ittyi approved these changes
LGTM〜

2024-03-20 03:23 UTC, merged