入力したデータを用いたエクセルファイル作成の本格導入
bob-g12/dayrepo-for-transportation pull request #52
Opened 2024-03-20 06:32 UTC by bob-g12

2024-03-21 03:24 UTC, bob-g12 commented
## 不確実要素の対応
### 想定していた不確実要素
- templateから、snippetのid(pk)のみを取得して、Viewでsnippetのpkと一致するデータを取得していたが、snippetがFKで取得していないテーブルを、そのテーブル内のsnippet_idと一致するデータの取得ができるのか、
- 上記に続き、そのデータが複数あった場合(工程テーブル)別々に入力ができるか？
### 発覚した不確実要素
- Excelファイルのセルの位置を直接名指しではなく変数など可変可能な状態から指定する方法
- 日付や時間のデータから、一部だけを指定する方法(年や分など、間に文字を挟みたいため)
- 日付から曜日を割り出す方法
## 解決法
#### snippetがFKを持っていないテーブルデータの取得
- 想定どおり、各テーブルが持ってるsnippet_id(FK)を取得したSnippetのid(FK元)と参照すると取得できました。
#### 取得するテーブルデータが複数の場合
- 単独のテーブルデータの取得にはget_object_or_404を使用していたが、複数データではget_list_or_404を用いることでlistでの取得ができた。[参考サイト](https://office54.net/python/django/views-get-404)
#### 編集するExcelファイルのセルの位置を可変可能にする
- 今回方法は見つけられなかったが、システム上上限も近く、問題はないため、すべてのパターンを記載
#### 日付や時間の一部を指定する方法
- 年は.year　月は.month　日は.day
- 時間は.hour　分は.minute　秒は.second
[参考サイト:時間](https://trends.codecamp.jp/blogs/media/column26)
[参考サイト:日付](https://trends.codecamp.jp/blogs/media/column25)
#### 日付から曜日を割り出す方法
- .weekdayで０から
- .isoweekdayで１から、月曜日からの順番で数値に変換可能
[参考サイト](https://note.nkmk.me/python-datetime-day-locale-function/)

2024-03-21 14:54 UTC, ittyi requested changes
コメントしました〜

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +    process_date = get_list_or_404(Process, snippet_id=snippet_pk)
単なるレコード全部を取ってきているだけっぽいので、date (日付)ではないような？🤔

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +        weekday = "日"
この処理はここに書くと excelfile_download 関数が長大になって冗長なので、excelfile_download 関数の外で関数化するといいと思う〜

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +    today_mileage = snippet_date.end_mileage - snippet_date.start_mileage
細かいけど改行したい
```suggestion

    today_mileage = snippet_date.end_mileage - snippet_date.start_mileage
```

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +    sheet["BD18"] = (
改行したい
```suggestion

    sheet["BD18"] = (
```

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +    work_hour = 0
改行したい
```suggestion

    work_hour = 0
```

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +    work_hour += snippet_date.driving_time.hour + snippet_date.non_driving_time.hour
この上の work_minute は 60  分を超えた場合の処理を追加していますが、ここの `work_hour += snippet_date.driving_time.hour + snippet_date.non_driving_time.hour` でも 24時間を超えた場合の処理は必要ないです？

システム的には可能に感じましたが、誤入力以外では基本的にはないと思うのでなしでよければかまいませぬ。

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +    sheet["BG18"] = str(work_hour) + ":" + str(work_minute)
改行したい
```suggestion

    sheet["BG18"] = str(work_hour) + ":" + str(work_minute)
```

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +    sheet["BI18"] = str(breek_in_hour) + ":" + str(breek_in_minute)
スクショのあたりもそうですが、括弧で括ったりくくらなかったり括ってるけど改行したりしてなかったりするのは統一したいすね

<img width="473" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/3e7f45de-acd1-4242-b2fd-eaedb9754852">

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
この for 文の中身、関数化できると思うー
イメージこんな感じです。
```
def process_insert(sheet, process, cell_list):
    sheet[cell_list[0]] = process.start_point
    sheet[cell_list[1]] = process.via_point
    sheet[cell_list[2]] = process.end_point
    sheet[cell_list[3]] = process.client
    sheet[cell_list[4]] = process.goods
    sheet[cell_list[5]] = process.load_situation
    if process.is_load_situation != False:
        sheet[cell_list[6]] = "良"
    if process.load_mileage != False:
        sheet[cell_list[7]] = process.load_mileage
    if process.hollow_mileage != False:
       sheet[cell_list[8]] = process.hollow_mileage
```

使う時のイメージ
```
process_cells =  [["C23", "G23", "O23", "X23, "AJ23", "AS23", "BD23", "BG23", "BI23"],
                              ["C25" "G25", xxxx]
                              ["C27 "xxxx", xxxx....]
                              ["xxxx" "xxxx", xxxx....]
                              ["xxxx" "xxxx", xxxx....]
                              ["xxxx" "xxxx", xxxx....]
                              ["xxxx" "xxxx", xxxx....]
]

for i in range(process_count):
    process_insert(
        sheet, 
        process_date[i], 
        process_cells[i]
    )
```

二次元配列の方が見づらいとか思うかもしれないが、ぶっちゃけ cell の指定は全部見づらいので。記述量を減らす方が認知負荷が減ると思う

2024-03-21 14:54 UTC, ittyi commented on dayrepo/snippets/views.py
> +    response = HttpResponse(content_type="application/vnd.ms-excel")
結局 application/vnd.ms-excel の指定だと xls を指定するみたいだが、あえて古い方を指定しているのには何か意図がある? 
https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

なければ、使用しているライブラリ的にもこっちだと思う。
```suggestion
    response = HttpResponse(content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
```

2024-03-21 15:08 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    work_hour += snippet_date.driving_time.hour + snippet_date.non_driving_time.hour
これは労働時間や出勤時間の総計なので24時間を超えることは矛盾とはならないので時間は24では繰り上げません。
もちろん意図して発生することでもありませんが

2024-03-21 15:45 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
つまり、セルの位置を直接指定してることがすでに分かりづらいので配列を挟んで短くした方がよいということですか？

その前提で質問ですが、記述は多いが直接的な記述と、記述は少ないが配列処理を挟む記述で天秤にかけてると思います。
では、前者は畳んでしまえばよくないですか？それだけで配列を用いた記述と同等以上の視認性になりますし、データが追いやすいかと思います。
畳むことを推奨または畳まれた際の目印となるようなコメントを残してもいいですし、

2024-03-21 15:48 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    response = HttpResponse(content_type="application/vnd.ms-excel")
動作確認して問題なければ変更します

2024-03-21 15:59 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    sheet["BI18"] = str(breek_in_hour) + ":" + str(breek_in_minute)
こちらで変更しました。
手動で行わないと文字数などの違いからこういったばらつきが生まれますね。今後も注視していきます

2024-03-21 16:19 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        weekday = "日"
[こちら](https://github.com/bob-g12/dayrepo-for-transportation/pull/52/commits/463710d68a3b5be28837c41d58a9cae8215f4ad6)で短縮してみました

2024-03-21 16:20 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    process_date = get_list_or_404(Process, snippet_id=snippet_pk)
データと言いたかったのでdataが正しいですかね？
変えておきます

2024-03-21 16:25 UTC, ittyi commented on dayrepo/snippets/views.py
> +        weekday = "日"
おぉ！そっちのやり方覚えたか！笑
すばら👏

2024-03-21 16:30 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    process_date = get_list_or_404(Process, snippet_id=snippet_pk)
[こちら](https://github.com/bob-g12/dayrepo-for-transportation/pull/52/commits/966f3f1505ad4b658cfae6e245571e304685bd2d)で対応しました

2024-03-21 16:39 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
配列にする場合、二次元配列ではなく、配列を持った変数を配列に並べるのはどうですか？
[変数 1,変数 2,変数 3,]
変数1 = ["AA1","AC2"]
のように、
逆に段階は増えますが、indexを数える必要がなく可読性は増すかと思います。

2024-03-21 16:39 UTC, ittyi commented on dayrepo/snippets/views.py
> +    process_date = get_list_or_404(Process, snippet_id=snippet_pk)
process_data は他と違って list で返ってくるので、同じ変数名じゃないほうがいいと思う〜

2024-03-21 16:43 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    process_date = get_list_or_404(Process, snippet_id=snippet_pk)
前回のコミットが割と大幅な修正となり、このあたりの変数名は影響範囲が広いと感じたため、事前に確認しますが、
命名はprocess_listでいいですか？

2024-03-21 16:46 UTC, ittyi commented on dayrepo/snippets/views.py
> +    process_date = get_list_or_404(Process, snippet_id=snippet_pk)
うむむー
まぁオッケーb

2024-03-21 16:50 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    process_date = get_list_or_404(Process, snippet_id=snippet_pk)
[変更しました](https://github.com/bob-g12/dayrepo-for-transportation/pull/52/commits/68393f664d13051d9628145cfa272b9614f2997e)

2024-03-21 16:56 UTC, ittyi commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
6 個のインデックスを数えるのにそんなに時間がかかるとは思えんが、その変数名によりそうかなー

2024-03-21 17:15 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
試運転は問題なかったですが
[これ](https://github.com/bob-g12/dayrepo-for-transportation/pull/52/commits/3aa62f6ad5a26c5b50a2e3f390ce3672adc7b103)でどうですか？

2024-03-22 05:47 UTC, ittyi commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
sell ([セール](https://ejje.weblio.jp/content/sell))  ではなく cell ([セル](https://www.ritsumei.ac.jp/se/rv/joen/09/excel/ex1.html)) ですね〜。

というのと、実際の配列は0から始まるけど 1から始まる配列名、そんなに読みやすいかなー🤔
まぁ bob 氏が読みやすいならいーと思ふ〜

強いて言えば、 max が6個までなのは仕様 って旨はコメント書いておかないとなぜ 6 個?なのかはわからないかもってぐらいかな。

2024-03-22 05:47 UTC, ittyi commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
あ、あと不要な改行は消してね〜

2024-03-22 05:50 UTC, ittyi commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
[Must]
また、Python の「型ヒント」というものを追加してほしいです。
初めての Django での独自関数の作成かと思うので初めてお願いするのですが、型ヒントを明示することにより「⁠コードの可読性向上⁠」⁠、「⁠IDEコード補完の充実⁠」⁠、「⁠静的型チェックの実行」といった静的型付け言語のようなメリットが得られます。

2024-03-22 06:56 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
どうですか？
cellも修正しました
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/ba2e37c1-967e-49af-8c0a-18a99b1a920b)

2024-03-22 08:00 UTC, ittyi commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
good !
ただその関数、 return  はしていないのではでは

2024-03-22 08:48 UTC, ittyi requested changes
very nits コメントしました〜

2024-03-22 08:48 UTC, ittyi commented on dayrepo/snippets/views.py
> +    # Excelを返すためにcontent_typeに「application/vnd.openxmlformats-officedocument.spreadsheetml.sheet」を        セットします。
「application/vnd.openxmlformats-officedocument.spreadsheetml.sheet」を セットは見ればわかるんじゃない？というより、コメントのあるなしに関わらず「application/vnd.openxmlformats-officedocument.spreadsheetml.sheet」の存在自体がよくわからないもの No.1 な気がする 笑

なぜ「application/vnd.openxmlformats-officedocument.spreadsheetml.sheet」を セットしたんだろうってことで、 .xlsx の話に触れたらよりわかりやすいコメントになりそう〜

2024-03-22 08:48 UTC, ittyi commented on dayrepo/snippets/views.py
> +# excelfile_download内で工程を入力する関数
改行入れたい
```suggestion

# excelfile_download内で工程を入力する関数
```

2024-03-22 08:48 UTC, ittyi commented on dayrepo/snippets/views.py
> +    process_count = len(process_list)
この変数、使用するところで宣言した方がスコープも狭くなる & 追いかけやすい & 脳のメモリを食わないと思う

※やらなくて良いけど、なんなら for ごと関数化しちまえばよかったな🤔
     ※そうすると関数名がやっていることの説明にもなるし、ぶっちゃけよしなにデータを入れてくれれば  excelfile_download 関数自体はデータの入れ方に関心はないので
    ※今回はそこまでやらなくていーよ

2024-03-22 10:20 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +                sheet["BI23"] = process_date[i].hollow_mileage
->openpyxl　が要らないということですね
削除しときます。

2024-03-22 10:49 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    process_count = len(process_list)
変更しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/52/commits/4074c9ec5958514e4e0df626c31eeed40893b3ec

2024-03-22 11:00 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    # Excelを返すためにcontent_typeに「application/vnd.openxmlformats-officedocument.spreadsheetml.sheet」を        セットします。
変更しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/52/commits/40b9a293326d039dd75b63e432387cdcf6d4aa6a

2024-03-22 11:10 UTC, ittyi reviewed
マジで最後 笑

2024-03-22 11:10 UTC, ittyi commented on dayrepo/snippets/views.py
> +    )
これって工程テーブルの枠なのかな?
違うなら統一感ないかも

2024-03-22 11:18 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    )
FK使っててイレギュラーだったので分けようと思ったら最後になってました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/52/commits/b7e3df8878bf1728928d6f15e47cc848c2fd1350

2024-03-22 11:19 UTC, ittyi approved these changes
LGTM〜

2024-03-22 11:19 UTC, merged