入力済みデータの編集機能を作成
bob-g12/dayrepo-for-transportation pull request #54
Opened 2024-03-24 07:02 UTC by bob-g12

2024-04-08 13:00 UTC, ittyi commented on dayrepo/snippets/views.py
> +                "checklist_id":checklist_id
```suggestion
                "checklist_id": checklist_id
```
くそ細かいが

2024-04-08 13:00 UTC, ittyi commented on dayrepo/snippets/views.py
> +    def post(self, request,checklist_id ):
```suggestion
    def post(self, request, checklist_id):
```
くそ細かいが

2024-04-08 13:02 UTC, ittyi commented on dayrepo/snippets/views.py
> +        checklist = Checklist.objects.get(pk=checklist_id)
100 行目の Checklist.objects.get(pk=checklist_id) とここの Checklist.objects.get(pk=checklist_id) は、やっていることが同じなのでどっかで一回読んで変数に入れれば十分だと思う〜

<img width="542" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/c9b06298-4cec-4271-86a1-c8138b76953c">

2024-04-08 13:03 UTC, ittyi commented on dayrepo/snippets/views.py
> +class ChecklistEditView(View):
ぱっと見の密集具合がやばい！笑
<img width="537" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/16a69481-ba55-4793-a6b9-ae1479fab7cb">

こういった文章見づらいと思うんだけどどう?
特に違和感なければこれは別に修正なくても大丈夫〜

2024-04-08 13:04 UTC, ittyi commented on dayrepo/snippets/views.py
> +        post = get_object_or_404(Checklist, pk=post_id)
post_id って言っているけど Checklist ...?

2024-04-08 13:05 UTC, ittyi commented on dayrepo/snippets/views.py
> +        edit_form = ChecklistForm(instance=post)
post って言っているけど ChecklistForm ....?

2024-04-08 13:06 UTC, ittyi commented on dayrepo/snippets/views.py
> +        return render(request, "checklist_edit.html", {'form': edit_form,'post':post})
```suggestion
        return render(request, "checklist_edit.html", {'form': edit_form})
```

みたk見た感じ、 'post':post は使われてなさそう??
<img width="1064" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/4e441968-b4de-4451-83fb-dbdd8073b72f">

2024-04-08 13:07 UTC, ittyi commented on dayrepo/snippets/views.py
> +        form = ChecklistForm(request.POST, instance=post)
ここも post_id だけど実態が Checklist になっていて違和感がある

2024-04-08 13:08 UTC, ittyi commented on dayrepo/snippets/views.py
> +class SnippetEditView(View):
か、改行...　笑
<img width="551" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/2798516b-9cc5-4926-81e8-5dc0404fb801">

特に違和感なければこれは別に修正なくても大丈夫〜

2024-04-08 13:10 UTC, ittyi commented on dayrepo/snippets/views.py
> +        return render(request, "snippet_edit.html", {'form': edit_SnippetForm,'form_trouble': edit_TroubleForm,'form_process': edit_ProcessForm,'process_count': process_len,'checklist_id':checklist_i
この行横に長すぎるかもー
フォーマッターのせいならしゃーないけど改行できないかやってみてくれん？
<img width="818" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/7c787274-9061-4172-b754-c746cf1e33c1">

2024-04-08 13:11 UTC, ittyi commented on dayrepo/snippets/views.py
> +
```suggestion
```
不要なコード

2024-04-08 14:01 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  if (now_count <= 6){
同様の修正があるためhttps://[こちら](github.com/bob-g12/dayrepo-for-transportation/pull/54#discussion_r1555772689)のレビューで同時に対応します

2024-04-08 14:01 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +      if (i != 8 && i <= 10){
同様の修正があるためhttps://[こちら](github.com/bob-g12/dayrepo-for-transportation/pull/54#discussion_r1555772689)のレビューで同時に対応します

2024-04-08 14:35 UTC, bob-g12 commented on dayrepo/snippets/forms.py
> +#         return str(obj.id) + " " + str(obj.working_day) + " " + obj.account_id.first_name + " " + obj.account_id.last_name + " " + obj.car_id.vehicle_number
手間かかった分名残り惜しかったが、いらんか

2024-04-08 15:04 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +    alert("工程を追加しますか？",);
文言は正直どうでもいい。アラートとして意味があるのかと、ないなら消したい。

というわけで後々検討するなら削除しましょう〜

2024-04-08 15:06 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  if (now_count <= 6){
自分で送ったb文章やリンクはちゃんとできているか確認したほうがいいかも〜
<img width="791" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/e7cc4686-3e1f-4b00-af44-5bbe6b5fcd2d">

こちらってどちら？

2024-04-08 15:16 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +      else if (i == 8){
[こちら](https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/6885935fd15511b3f1330c7be793fbdd8a59d637)でまとめて修正しました

2024-04-08 15:23 UTC, bob-g12 commented on dayrepo/snippets/templates/checklist_edit.html
> +        <h2>点検項目項目</h2>
フォームのデザインを変える際にこちらの変更も必要になってくると思うので、その時その案にあわせた対策をとった方がいいかと思います。

2024-04-08 15:29 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  if (now_count <= 6){
https://github.com/bob-g12/dayrepo-for-transportation/pull/54#discussion_r1555772689
こちらで確認ください

2024-04-08 15:29 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +      if (i != 8 && i <= 10){
https://github.com/bob-g12/dayrepo-for-transportation/pull/54#discussion_r1555772689
こちらで確認ください

2024-04-08 15:32 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("edit/<int:post_id>/", views.snippet_edit,name="snippet_edit"),
動作/対象/引数で並べた方が統一感あるように見えますが変えるべきですか？

2024-04-08 15:36 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("post/snippet/<int:checklist_id>/", views.snippet_post,name="snippet_post"),
[こちら](https://github.com/bob-g12/dayrepo-for-transportation/pull/54#discussion_r1556047675)の考えもあるのでsnippetを省略する方を選択します

2024-04-08 15:37 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("edit/<int:post_id>/", views.snippet_edit,name="snippet_edit"),
snippets/edit/<post_id>/ は 動作/対象/引数 ではなく、サービス(対象)/動作/引数 になっているよ

2024-04-08 15:38 UTC, ittyi commented on dayrepo/snippets/templates/checklist_edit.html
> +        <h2>点検項目項目</h2>
デザインの話ではなく、htmlとしてのあるべきの話でもあるので、特段中に入れる意味がないなら今外に出してほしいです〜

2024-04-08 15:44 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +    alert("工程を追加しますか？",);
動作にメリハリをつけることや、ダイアログを表示したときと挙動が近いため、文章を変えて"工程を追加します"に変えることで暫定的な表示にしてはいけないですか？

2024-04-08 15:54 UTC, ittyi requested changes
ぱっと見でどーん

2024-04-08 15:54 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +let limit = 6;
```suggestion
const limit = 6;
```

2024-04-08 15:54 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +let bool_select = 8;
```suggestion
const bool_select = 8;
```

2024-04-08 15:54 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +let not_select = 10;
```suggestion
const not_select = 10;
```

2024-04-08 15:54 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  let now_count = count + 1;
```suggestion
  const now_count = count + 1;
```
よくみたらこれも変更されてないね

2024-04-08 15:54 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> -let i = 1 ;
[念の為]
i 消してるけど大丈夫？
動作確認していればOKです〜

2024-04-08 15:54 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  }
大きい if 文ができた時、早期 return が使えないかどうかは確かめてみるといいよ〜

```suggestion
  if (now_count > limit){
    alert("これ以上増やせません");
    return ;
  }
  
  alert("工程を追加しますか？");
  const content_area = document.getElementById("form_area");
  let clone_element = content_area.cloneNode(true);
  let content_clone = document.getElementById("add_space");
  const content_count = content_area.childElementCount;
  for (let i=0; i<content_count; i++){
    if (i != bool_select && i <= not_select){
      clone_element.children[i].children[1].value="";
    }
    else if (i == bool_select){
      clone_element.children[i].children[1].checked="";
    }
  }
  content_clone.before(clone_element)
  document.getElementById("count").innerHTML = now_count;
  clone_element.id = now_count;
```

2024-04-08 15:54 UTC, ittyi commented on dayrepo/snippets/templates/snippet_post.html
> +        <div id= "add_space">
```suggestion
        <div id="add_space">
```
どうでもいい修正

2024-04-08 15:54 UTC, ittyi commented on dayrepo/snippets/templates/snippet_list.html
> +    <p class="checklist">{{ checklist }}</p>
```suggestion
    <p id="checklist">{{ checklist }}</p>
```
idで良さそう〜

2024-04-08 15:54 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +    alert("工程を追加しますか？",);
ここ読んだ？
https://github.com/bob-g12/dayrepo-for-transportation/pull/54#discussion_r1555762535

私が気にしているのは、「アラートは出たけどどちらにせよ工程を追加するみたいな挙動にはなっていないかな？というのだけ確認してほしいかも〜」というところだよ。アラートが出ていて、そのアラートで「追加しますか？」と聞いているけど、やっぱりやめた。ってことは今のコードで既にできている？できていない？
できているなら別にそのままでもいいし、できていないなら無意味なので直してほしい。

2024-04-08 15:56 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +    alert("工程を追加しますか？",);
質問に答えてほしいのだけど、今のままだとアラートが出てもどちらにせよ フォームは追加される挙動になっている。ってことでいい？

2024-04-08 16:10 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("edit/<int:post_id>/", views.snippet_edit,name="snippet_edit"),
最初のsnippetsはサービスの総称だからよいかと、故にアプリケーションの名前なわけですしおs
であればsnippetもパスからなくすのではなく別の表記の方がまだわかりやすいかも

2024-04-08 16:10 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        checklist = Checklist.objects.get(pk=checklist_id)
[対応しました](https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/03e0895eb8f13e095a9c5e7a595d92572be37082)

2024-04-08 16:16 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +class ChecklistEditView(View):
フォーマット整理しました

2024-04-08 16:30 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        post = get_object_or_404(Checklist, pk=post_id)
全体的にurlからviewの中でpost_idという引数表現をやめました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/444d3c68a5d45e34935d4a74a1cc8f33fb1148c2

2024-04-08 16:34 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        edit_form = ChecklistForm(instance=post)
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/ca0196fb31e895193280ca361af400cffa040b8c

2024-04-08 16:35 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        form = ChecklistForm(request.POST, instance=post)
同様のレビューで対応済みです

2024-04-08 16:36 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +class SnippetEditView(View):
同様のレビューで対応済みです

2024-04-08 16:38 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        return render(request, "snippet_edit.html", {'form': edit_SnippetForm,'form_trouble': edit_TroubleForm,'form_process': edit_ProcessForm,'process_count': process_len,'checklist_id':checklist_i
同様のレビューで対応済みです

2024-04-08 16:44 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("edit/<int:post_id>/", views.snippet_edit,name="snippet_edit"),
>総称だからよいかと

ん？何かいいんですか？

>別の表記の方が

イメージしているものがわからないので、ぜひ書いてみてください〜

2024-04-08 16:46 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +    alert("工程を追加しますか？",);
OKです

2024-04-08 16:49 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> -let i = 1 ;
iの代わりに取得したカウントを足すので不要です

2024-04-08 17:07 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +    alert("工程を追加しますか？",);
いい？ってbool型の返事で回答できる問かと思いました。
動作確認したうえで現在の動作は想定通りのものです。理由は上記の通りで、メッセージは似つかわしくないので変更済みです

2024-04-08 17:11 UTC, bob-g12 commented on dayrepo/snippets/templates/checklist_edit.html
> +        <h2>点検項目項目</h2>
一行ずらすだけでもあるので変えておきました

2024-04-08 17:47 UTC, ittyi requested changes
コメントしました〜

2024-04-08 17:47 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  now_count += 1;
こうすると const にできて、変数も一つ減らせます〜
変数名は適当なので、好きに修正してください。

もし以下をそのまま使う場合、こちらも一緒にマージしてください: 

```suggestion
  const now_count = Number(document.getElementById("count").innerHTML);
  if (now_count == limit){
    alert("これ以上増やせません")
    return
  }
  alert("工程を追加します");
  const count_plus1 = now_count += 1;
```

2024-04-08 17:47 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  clone_element.id = now_count;
```suggestion
  document.getElementById("count").innerHTML = count_plus1;
  clone_element.id = count_plus1;
```

2024-04-08 17:47 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  content_clone.before(clone_element)
細かいですが、基本的に変数は出来るだけ使用する箇所の近くに置きたいです〜
認知負荷も下がります

```suggestion
  const content_count = content_area.childElementCount;
  for (let i=0; i<content_count; i++){
    if (i != bool_select && i <= not_select){
      clone_element.children[i].children[1].value="";
    }
    else if (i == bool_select){
      clone_element.children[i].children[1].checked="";
    }
  }
  
  let content_clone = document.getElementById("add_space");
  content_clone.before(clone_element)
```

2024-04-08 17:47 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("edit/<int:post_id>/", views.snippet_edit,name="snippet_edit"),
checklist_id どっから出てきた....?

2024-04-08 17:47 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  if (now_count == limit){
これ、境界値のテストは行いましたか？(今回で言うと6個?フォームが作れて、7個目で失敗するかどうか。

また、今後のコードの変更やバグの埋め込みやすさなどを考えると、 == で完全一致するより、 <= や >= などを利用して、何々以上は全てだめ。と言ったように全域的に防御した方がコードの保守性が高いです〜

2024-04-08 18:20 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  now_count += 1;
実装しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/12d6a8f19c912cb1c754ceb1188e060aecf0f100

2024-04-08 18:23 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  content_clone.before(clone_element)
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/951e5383fc8247294b02a6cb3fcbbe7434089940

2024-04-08 18:25 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  if (now_count == limit){
万が一突破された時のために守備範囲広げといた方がいいってことか

2024-04-09 02:44 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  now_count += 1;
動作確認しましたか？
now_count が宣言されずいきなり出てきているように見えます

2024-04-09 02:46 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  content_clone.before(clone_element)
そのコミットの中で、content_clone が対応されていないです〜

それで言うと、content_clone と

2024-04-09 02:47 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  if (now_count == limit){
>守備範囲広げといた方がいい

イエス！
突破するのはユーザーかもしれないし、 bob 以外の実装者かもしれぬ。
あと、境界値のテストは行いましたか？(今回で言うと6個?フォームが作れて、7個目で失敗するかどうか。

2024-04-09 02:50 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("edit/<int:post_id>/", views.snippet_edit,name="snippet_edit"),
あぁ、もうコード側が変わってるのね。リー

2024-04-09 03:04 UTC, ittyi requested changes
コメントしました〜

2024-04-09 03:04 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  let count = Number(document.getElementById("count").innerHTML);
この書き方だと、万が一 Number 型に変換できない値が getElementById("count").innerHTML に入ってくる可能性があって危険だから、if 文で 型チェックをした上で count 変数に格納しましょう〜

ここら辺を使うといいです
https://uxmilk.jp/46961

2024-04-09 03:04 UTC, ittyi commented on dayrepo/snippets/views.py
> +        checklist = Checklist.objects.get(pk=checklist_id)
変換 はしていないので、コードの実態とコメントを合わせよう〜

2024-04-09 08:38 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  if (now_count == limit){
しました
異常なしです

2024-04-09 08:44 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  content_clone.before(clone_element)
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/76c3d6032c58d351610d5ceeffbdc6d8ba925bf4

2024-04-09 08:45 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  now_count += 1;
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/cf039fa481f1b5122f41c1d1896182caba01e84b

2024-04-09 08:49 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +    }
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/35e04f8ebb59429cddd6b84f1bfde7586eb6c038

2024-04-09 08:55 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  const not_select = 10;
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/77ebe8972ae34bb56e6d8574e811c55519feb56f

2024-04-09 08:57 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
>  const addForm = () => {
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/b9491591994b313e8703be698573302c6c6f1721

2024-04-09 09:35 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  let count = Number(document.getElementById("count").innerHTML);
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/c9b9796b1f3eef553cc09865b2921f9aeb2c5bf0

2024-04-09 09:35 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        checklist = Checklist.objects.get(pk=checklist_id)
整理しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/b9491591994b313e8703be698573302c6c6f1721

2024-04-09 10:13 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
>  const addForm = () => {
addForm 全体の話です〜
<img width="511" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/090ac2a1-4a69-4761-bcd5-a140edff0e50">

どことどこの処理がブロックなのかがわからず、関数の中身の処理が全て一連になっているので改行しましょう〜

2024-04-09 10:15 UTC, ittyi commented on dayrepo/snippets/views.py
> +        checklist = Checklist.objects.get(pk=checklist_id)
フォーマット整理?

2024-04-09 10:18 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  now_count += 1;
count += 1; とするのではなく、
```
document.getElementById("count").innerHTML = count + 1;
  clone_element.id = count + 1;
```

とすれば大元の変数を const にできる & count += 1;  とする箇所と実際に使用する箇所が離れないと思います〜

2024-04-09 11:30 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
>  const addForm = () => {
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/856acb4bcdcfa5dd23e4ee0a34a35b03f159d4eb

2024-04-09 11:32 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        checklist = Checklist.objects.get(pk=checklist_id)
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/fc78ab646d588b239d5167acc19f82abe85e45e4

2024-04-09 11:39 UTC, bob-g12 commented on dayrepo/snippets/static/js/process_add.js
> +  now_count += 1;
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/b7c8ba224ac1053865a24b1dc32924532f04ccc3

2024-04-09 12:38 UTC, ittyi requested changes
最後です〜(たぶん)

2024-04-09 12:38 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +  let count = Number(
```suggestion
  const count = Number(
```

2024-04-09 12:38 UTC, ittyi commented on dayrepo/snippets/static/js/process_add.js
> +    return
セミコロンはつけるならつけるで統一しましょう〜
```suggestion
    return ;
```

他の addForm の中も全部お願いしますます

2024-04-09 14:22 UTC, ittyi reviewed
最後〜

2024-04-09 14:22 UTC, ittyi commented on dayrepo/snippets/views.py
> +        checklist.pk = checklist_id
[Q]
ここって使ってる？

使ってなければ消そうずら
```suggestion
```

2024-04-09 14:30 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        checklist.pk = checklist_id
こちらの方で削除しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/54/commits/ea784ff50c97bc6a8ef63c091cce9114e0030495

2024-04-09 15:25 UTC, ittyi approved these changes
LGTM~

2024-04-09 15:25 UTC, merged