投稿データの削除機能作成
bob-g12/dayrepo-for-transportation pull request #56
Opened 2024-04-12 12:33 UTC by bob-g12

2024-04-12 13:05 UTC, bob-g12 commented
オール削除という名前が気持ち悪いので別の名前の方がいいかもしれない

2024-04-13 15:35 UTC, ittyi requested changes
コメントしました〜

2024-04-13 15:35 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("delete/<int:post_id>/<str:post_type>/", views.post_delete,name="post_delete"),
```suggestion
    path("delete/<int:target_id>/<str:delete_type>/", views.post_delete,name="post_delete"),
```

他のコードの箇所では post_id と checklist_id は明確に別物として扱っていて、その上でこのパスにはどっちが渡ってくるかわからなくなっているので、1段階抽象度を上げた命名にするといいと思う〜

あと post_type だと postの種類って意味になるけど、あくまでも削除する種類だと思うのでこっちは delete ってつけた方がわかりやすいと思う〜

2024-04-13 15:35 UTC, ittyi commented on dayrepo/snippets/views.py
> +        if post_type == "snippet":
if 文の中身が結構長いので、PostDelete というクラスを折角定義しているわけだし if 文それぞれで メソッド化した方が、一つのメソッドあたりのスコープが狭くなるので可読性が高いです〜

2024-04-13 15:35 UTC, ittyi commented on dayrepo/snippets/views.py
> +                process[i].delete()
ここ、配列に対するインデックスアクセスを使わずに. イテラブルオブジェクトをそのまま指定してfor を回して削除できませんか？
https://www.bold.ne.jp/engineer-club/python-for

一応その方が現代的な書き方なのと、今後の書き換えも多少安全になるので買いてみてほしいです〜
やってみてできなかったら一旦インデックスアクセスでいいです

2024-04-13 15:35 UTC, ittyi commented on dayrepo/snippets/templates/snippet_list.html
> +    <button onclick="location.href='{% url 'post_delete' post.id 'all' %}'">オール削除</button>
一旦画面上でだけの命名になりますが、以下でどうですか？
```suggestion
    <button onclick="location.href='{% url 'post_delete' post.id 'all' %}'">一括削除</button>
```

2024-04-14 10:41 UTC, bob-g12 commented on dayrepo/snippets/templates/snippet_list.html
> +    <button onclick="location.href='{% url 'post_delete' post.id 'all' %}'">オール削除</button>
ありっすね

2024-04-14 12:02 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +                process[i].delete()
出来ました
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/7f10df2bbbab9c820de54e0ba76a67f885c5a9ea

2024-04-14 12:07 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("delete/<int:post_id>/<str:post_type>/", views.post_delete,name="post_delete"),
viewの記載も変える必要があるためこちらで対処しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/774bd07638c22c167e4a9aab8cd276b93c33afc1

2024-04-16 16:58 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        if post_type == "snippet":
呼ぶ用の集約メソッドで対応しました。

2024-04-16 17:42 UTC, ittyi requested changes
コメントしました〜

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +class post_del_pattern():
私の適当なスマホコーディングも悪かったですが、クラス名なのでアッパーキャメルケースでお願いします〜
また、このクラスは削除系のものを集めたもの。でしかないので、 post かどうか。と言う情報は不要だろ思います。

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +    def snippet_del(request,target_id):
不要な引数は消しましょう
```suggestion
    def snippet_del(target_id):
```

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +    def checklist_del(request,target_id):
不要な引数
```suggestion
    def checklist_del(target_id):
```

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +    def all_del(request,target_id):
不要な引数
```suggestion
    def all_del(target_id):
```

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +
```suggestion
    if delete_type == "snippet":
        del_class.snippet_del(target_id)
    elif delete_type == "checklist":
        del_class.checklist_del(target_id)
    elif delete_type == "all":
        del_class.all_del(target_id)
        
    return redirect(to="snippet_list")
```

if-elif 文はどれかが一つ呼ばれたら他に入ることはないのと、redirect の内容が全く同じなので、1箇所で十分です

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
とりあえず今回追加したメソッドや関数だけでも構わないので、型ヒントを全てに追加してください。

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +        checklist.delete()
改行してください〜
```suggestion
        checklist.delete()

```

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +        snippet.delete()
snippet の delete をあえて下で行っている意図はありますか？なければ、 get の直下でいいと思います〜

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +            process_object.delete()
process は既にオブジェクトなので、オブジェクトオブジェクトみたいな命名になっているのと、object とつけることにさほど名前としての意味がないです。

こっちの命名の方が意味があるかつシンプルでいいと思います〜
```suggestion
        process_list = get_list_or_404(
            Process, snippet_id=target_id
        )
        for process in process_list:
            process.delete()
```

2024-04-16 17:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +        checklist.save()
snippet と dutiestrouble と process は削除するけど checklist は削除せずに bool を変更するだけ。と言う意味では「違う処理をしている」ので、この checklist の一連の処理だけ snippet_del の冒頭か一番最後で行うといいと思います〜

こういう場合は簡単でもいいので以下のようなコメントがあってもいいと思います。
```
# 日報だけを削除時、点検項目は未提出状態にする
checklist = Checklist.objects.get(
            pk=snippet.checklist_id.id
        )
        checklist.is_snippet_make = False
        checklist.save()

# 日報, 業務トラブル, 工程 の削除
```

2024-04-17 17:54 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +
拡張性と説明性下がらないですか？

2024-04-17 17:57 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        snippet.delete()
processはsnippetから外部キーを取得しておりまして、先にsnippetの削除はできないので最後にしてます

2024-04-17 17:59 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        checklist.save()
コメントで補足を入れておきます。

2024-04-17 18:00 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +            process_object.delete()
process_object と processのネーミングの変更対応します

2024-04-17 18:01 UTC, bob-g12 commented on dayrepo/snippets/views.py
了解です

2024-04-17 18:09 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +def post_delete(request, target_id, delete_type):
削除機能において、送る機能はありませんがなにを送れていればよいのですか？

2024-04-17 18:09 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +class post_del_pattern():
変えておきます

2024-04-17 23:36 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +class post_del_pattern():
変更しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/1bc1cc29a1af666a378d83c4c71e7354aeba4fc3

2024-04-17 23:41 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +            process_object.delete()
命名変更しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/8f5e7e0518f76f207fa40e23eff259c00e39ee68

2024-04-18 00:07 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        checklist.save()
コメント追加しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/f3f17ebeaa6e651a84410a16245afece832e98e0

2024-04-18 00:28 UTC, bob-g12 commented on dayrepo/snippets/views.py
記載しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/d301922319e46c8c58b6a65d368f4df334c58dd3

2024-04-18 00:47 UTC, ittyi commented on dayrepo/snippets/views.py
> +class post_del_pattern():
post かどうか、は関係ない挙動のメソッド(というか、deleteは厳密には http メソッドは post ではなく delete
にするべきだが、一旦見逃している) なので、postという情報はいらないと思います。

また、変数も関数も同じですが、プログラムが扱うもののほぼ全てがデータなので、Dataという単語もあまり意味がないと思います〜

2024-04-18 00:47 UTC, ittyi commented on dayrepo/snippets/views.py
> +    def snippet_del(request,target_id):
requestではなく、self ではありませんか？

2024-04-18 00:48 UTC, ittyi commented on dayrepo/snippets/views.py
> +
どういった理由でそう感じましたか？
※ここが大事

2024-04-18 00:49 UTC, ittyi commented on dayrepo/snippets/views.py
> +def post_delete(request, target_id, delete_type):
httpメソッドがpostで送れていればいいかと思います。
少なくとも get ではないですね。
※あくまでも推測なので、実際のrequestがどう飛んでいるのかは確認してください〜

2024-04-18 00:52 UTC, ittyi commented on dayrepo/snippets/views.py
> +        snippet.delete()
というのはパッと見でわからないのと、それなら Snippet の取得自体も最後に行えばいいかなと思います〜

ポイントは Snippet を取得したけど、あれ？まだ使われないな…と脳内メモリを食うことなので〜

2024-04-18 00:53 UTC, ittyi commented on dayrepo/snippets/views.py
> +        checklist.save()
指摘しているのはコメントだけではないです〜

2024-04-18 04:30 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +class post_del_pattern():
今後別の削除機能を追加したときのことを危惧しての命名でしたが、このクラスの中に新しいメソッドを作ってしまえば良さそうなのでDeletePatternに変えときます

2024-04-18 04:32 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +class post_del_pattern():
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/2f655d762abf26d26935d11fa378ada2b9ea90a1

2024-04-18 05:04 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    def snippet_del(request,target_id):
受け取るべき引数が一つ受け取れていないとエラーで確認できたのでrequestを追加したところ作動しました。
printで確認したところ、関数の第一引数ではrequestを、クラス側ではインスタンスを受け取っていたことが分かったので、
クラス内関数ではself、関数側ではrequestで受け取っておきます。
[参考サイト](https://kanda-it-school-kensyu.com/python-basic-contents/pbc_ch03/pbc_0303/)
[プッシュ](https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/cb9dd17271f96124370b5236ba0848b4c1fe3720)

2024-04-18 05:14 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +
この処理を後々、ユーザー情報や車両情報の処理にも併用したいと考えていたので、その場合、操作する画面(戻りたい画面)が異なることも考えられ、別々の方がいいかと思います。
※拡張性と説明性については、elifの一つをelseに変えるのかと思い書いてしまいました。

2024-04-18 05:18 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +def post_delete(request, target_id, delete_type):
削除のリクエストは以下のように
 "GET /snippets/delete/43/checklist/ HTTP/1.1" 302 0
となっており、対象のデータを取得した延長の処理かと

2024-04-18 05:22 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        snippet.delete()
他のテーブルデータを取得するためにsnippetは取得する必要があるため順番は変えられません

2024-04-18 05:30 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        snippet.delete()
checklistの編集のみ、snippetを取得してから削除までの間でないといけないためできる限り下に移しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/d85ad5ef55d40280a069bcca29d2956a0148b4ca

2024-04-18 05:31 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        checklist.save()
snippetの取得同様に、最後にはできなかったので、できる限り下へ移動しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/d85ad5ef55d40280a069bcca29d2956a0148b4ca

2024-04-18 07:44 UTC, ittyi commented on dayrepo/snippets/views.py
> +class post_del_pattern():
そのクラスって、何を削除する系のメソッドを集める？
DBに関するものだけなら、それはわかる命名でもいいかも〜

2024-04-18 08:04 UTC, ittyi commented on dayrepo/snippets/views.py
request の方は any じゃなくい型を指定できるね。
※公式を見る限り、 self は型ヒントいらない: https://www.python.jp/news/wnpython311/typing2.html

any を出来るだけ避けたい理由もちゃんとあるので、他の言語だけどここら辺を見てみてください〜
https://zenn.dev/nyaity_boo/articles/d122c3389f175d
> 型安全性：　コンパイルエラーにより型のエラーに瞬時に気づく。エディタがリアルタイムにエラーを教えてくれる。
（とにかくエラーは可能な限りコンパイラでで弾くことが望ましい。）
エディタの補完機能によるコーディング加速、コーディングミスの軽減
可読性の向上。　source code is a document.

上記3つのメリットはPythonでも同様です〜

2024-04-18 08:12 UTC, ittyi commented on dayrepo/snippets/views.py
> +
> 併用したい

既に 3 ケースで同じことがわかるように、snippet_list 画面は現状 top 画面でもあるので、基本的に if 文を抜けたら snippet_list 画面になることが多いと思います.
その他の画面に飛ぶケースがあったとしても(とはいえ、 おそらくユーザー情報や車両情報を削除するときも完了後 top ページに遷移するのが普通のUXではあるので、 基本的に少ないとは思う) 、その場合でのみ return を書く方がむしろ読みやすいと感じました。

例として、仮に別のものを追加して 6 個とかになったとしましょう。

その場合以下のようになりますが、どちらの方が視認性がいいと思うかな？
※以下のコード自体は仮です。
#### 元の書き方
```
    if delete_type == "snippet":
        del_class.snippet_del(target_id)
        return redirect(to="snippet_list")
    elif delete_type == "checklist":
        del_class.checklist_del(target_id)
        return redirect(to="snippet_post")
    elif delete_type == "all":
        del_class.all_del(target_id)
        return redirect(to="snippet_list")
    elif delete_type == "user":
        del_class.all_del(target_id)
        return redirect(to="snippet_list")
    elif delete_type == "car":
        del_class.all_del(target_id)
        return redirect(to="snippet_list")
    elif delete_type == "login_user":
        del_class.all_del(target_id)
        return redirect(to="snippet_list")
```

#### 共通で一覧を用意した上で、違うところだけ明記するやり方
```
    if delete_type == "snippet":
        del_class.snippet_del(target_id)
    elif delete_type == "checklist":
        del_class.checklist_del(target_id)
        return redirect(to="snippet_post")
    elif delete_type == "all":
        del_class.all_del(target_id)
    elif delete_type == "all":
        del_class.all_del(target_id)
    elif delete_type == "all":
        del_class.all_del(target_id)
    elif delete_type == "all":
        del_class.all_del(target_id)
        
    return redirect(to="snippet_list")
```

2024-04-18 08:16 UTC, ittyi commented on dayrepo/snippets/views.py
> +def post_delete(request, target_id, delete_type):
削除するリクエストで GET で送られているのはやはりおかしいですね。

2024-04-18 08:18 UTC, ittyi commented on dayrepo/snippets/views.py
> +        snippet.delete()
snippet.delete() を行った後に id って取得できないのかな？
できるような🤔

2024-04-18 08:24 UTC, ittyi commented on dayrepo/snippets/views.py
> +        checklist.save()
コメントを確認しましたが、私が言っているのは関数に対するコメントではなく、該当処理に対してコメントを残す方がわかりやすいという意味の指摘です。
https://github.com/bob-g12/dayrepo-for-transportation/commit/f3f17ebeaa6e651a84410a16245afece832e98e0

>対象のsnippetと、
    # snippet_idを取得したdutiestroubleとprocessの削除
    # 更にchecklistのsnippet判定カラムの値をFalseへ

というコメントを関数の上に書くのではなく、 該当処理の真上に「その行では何をしているのか」を書いた方がコードを読むときにわかりやすいと思います〜

2024-04-18 17:08 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +class post_del_pattern():
DbDeletePatternで対応しました
[](https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/795ebf628dfba24a94f2f22bd36fac68d3108915)

2024-04-18 17:22 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +
違うところだけ明記することは賛成ですね。
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/f44997524d103e88a795f92c7be827936a6ac176

2024-04-18 17:44 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +def post_delete(request, target_id, delete_type):
リクエストのメソッドをDELETEにする必要があるということですか？

2024-04-18 18:02 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        snippet.delete()
動作確認したところ、エラーもなく正常にカラム値の変更ができたので変更しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/26b0fd67520bd9af3017caf296e20a3ebfa619e6

2024-04-18 18:41 UTC, bob-g12 commented on dayrepo/snippets/views.py
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/24b9396f621ab78b4edb318cf43effe818ad03df

2024-04-19 05:39 UTC, ittyi commented on dayrepo/snippets/views.py
> +def post_delete(request, target_id, delete_type):
そうです〜
なので以下で ` if request.method != 'POST':` というように狙ったメソッドかどうかを確かめる例外処理を入れてほしいと伝えていました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56#discussion_r1567722810

POST でも一応いいとは思いますが、メソッドの意味合いとしては DELETE が正しいです。
https://apidog.com/jp/blog/delete-method-introduction/
> なぜDELETEメソッドを見るのが少ない感じがある？
DELETEメソッドが実際にはあまり利用されていない大きな原因の1つは、**多くのAPIがRESTの設計規範に厳密には遵守していないことにある**と言えます。例えば、**多くのAPIはREST原則から外れたAPI設計をしている場合が多く、データ変更（添削や更新など）に関する全ての操作もPOSTメソッドによって実現されています。**
> また、リソースを削除すると、復元することが難しいので、セキュリティ面での考慮のため、リソースを削除することより、リソースを無効化にした方が安全になるので、DELETEメソッドの使用頻度がさらに下がります。
> このように、実用性を重視するためにRESTの原則が守られていないことが多いとはいえ、RESTの設計規範にきちんと遵守すると、APIの数が多くなっても、混乱せず効率的に管理できるのでしょう。

2024-04-19 06:30 UTC, ittyi commented on dayrepo/snippets/views.py
タプルではあるかもしれませんが、HttpRequestオブジェクト なんじゃないかな?と感じたんだけどどうだろう🤔ﾃﾞｷﾙｶｼﾗ
<img width="584" alt="image" src="https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/ea9e4f00-f596-4f8f-869b-be9dfff6bc66">
https://chuna.tech/blog/web-application/Django/about-request-in-django/

型チェックはそれで通っちゃうかもしれないけど、タプルだと抽象度がかなり高いので可読性的に何が入ってくるのかを自明にしたいすね

2024-04-19 10:07 UTC, bob-g12 commented on dayrepo/snippets/views.py
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/b894d9ece50a477818855a17cfd1104ea35b8346

2024-04-20 02:52 UTC, ittyi requested changes
最後になると思います〜

2024-04-20 02:52 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("delete/<int:target_id>/<str:delete_type>/", views.db_delete,name="post_delete"),
post  って命名は残す？メソッドに合わせる？
```suggestion
    path("delete/<int:target_id>/<str:delete_type>/", views.db_delete,name="db_delete"),
```

2024-04-20 02:52 UTC, ittyi commented on dayrepo/snippets/views.py
> +        # snippetと紐づいたdutiestroubleの削除
これみればわかるくない？（再燃 笑
```suggestion
```

2024-04-20 02:52 UTC, ittyi commented on dayrepo/snippets/views.py
> +        # snippetと紐づいたprocessの削除
これみればわかるくない？（再燃 笑
```suggestion
```

2024-04-20 02:52 UTC, ittyi commented on dayrepo/snippets/views.py
> +        # checklistのみの投稿として表示、判定させる
ちょびっとわかりづらいかも。

> 対象のsnippetが削除されたことを反映し、

ここいらないんじゃないかな？
というのと、　「checklistのみの投稿」がどういう状態なのかをもっと明記するといいかも〜
このアプリで言うと未提出状態かな？

2024-04-20 02:52 UTC, ittyi commented on dayrepo/snippets/views.py
> +    # 未提出postdataのchecklistを削除する
このメソッド的には、　post かどうかには関心がないと思う〜
post に関する情報をここに付与してしまうと、それは依存関係が出来上がっていることにもなるので、いらないと思います。
```suggestion
    # 未提出 data の checklist を削除する
```

2024-04-20 02:52 UTC, ittyi commented on dayrepo/snippets/views.py
> +    # 提出済みpostdataをすべて削除する
このメソッド的には、　post かどうかには関心がないと思う〜
post に関する情報をここに付与してしまうと、それは依存関係が出来上がっていることにもなるので、いらないと思います。
```suggestion
    # 提出済み data をすべて削除する
```

2024-04-20 02:52 UTC, ittyi commented on dayrepo/snippets/views.py
> +def db_delete(request:HttpRequest, target_id:int, delete_type:str):
埋もれていそうなので改めて
https://github.com/bob-g12/dayrepo-for-transportation/pull/56#discussion_r1571831208

2024-04-20 02:52 UTC, ittyi commented on dayrepo/snippets/views.py
> +        del_class.all_del(target_id)
一連の if 文とこの関数の return は別の処理なので、改行したいです〜
```suggestion

        del_class.all_del(target_id)
```

2024-04-20 02:52 UTC, ittyi commented on dayrepo/snippets/views.py
> +    del_class = DbDeletePattern()
クラスのインスタンスなので、クラスであることは自明なため何も説明していない変数名になっているような気がしました〜（ひと画面に収まっているため、DbDeletePattern がすぐ視界に入ると言う意味も含め。

DbDeletePattern のインスタンスなので、そのまま pattern という変数名はいかがでしょ？pattern.snippet_del などで呼ぶのは使用箇所でも説明になっていていいかもと思いました〜

他にも
- del_pattern
- query
- スコープが狭いので、いっそ意味をなくして視認性だけを上げる ddp 
などはいかがでしょうか？

2024-04-20 12:03 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +def post_delete(request, target_id, delete_type):
POSTメソッドになるように変更しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/bea571db303c2b898d90d8a66e38064b1fefdc19

2024-04-20 12:12 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("delete/<int:target_id>/<str:delete_type>/", views.db_delete,name="post_delete"),
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/9b7423f4332aa675cccfde71a8615cb1d5dc3e8d

2024-04-20 12:22 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        # checklistのみの投稿として表示、判定させる
> 対象のsnippetが削除されたことを反映し

反映したというような言葉がないとカラム値をFarseに変えたことへの説明がないので、たった二文字で表せるならあってもいいかと思います。
未提出状態は納得です。変更しておきます。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/39242b59e856b9a8f09c1d7b6d9ff7908622f421

2024-04-20 12:28 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +def db_delete(request:HttpRequest, target_id:int, delete_type:str):
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/89b3209dd727c1f5aa6a9070174fea612928c996

2024-04-20 12:30 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +    del_class = DbDeletePattern()
del_patternが意味合いとしてもしっくりきました。
対応しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/483772474a7a3f1bf892f7be17be5d60add14c93

2024-04-20 12:42 UTC, ittyi commented on dayrepo/snippets/views.py
> +        # checklistのみの投稿として表示、判定させる
> 反映したというような言葉がないとカラム値をFarseに変えたことへの説明がない

それで言うと、反映という言葉に カラム値をFarseに変えたこと と言う意味合いは感じ取れなかったので、反映という二文字の問題ではないように感じました。

# 対象のsnippetが削除されたとき、
# 未提出日報として表示、判定させる

とかはどうでしょ？

2024-04-20 12:47 UTC, bob-g12 commented on dayrepo/snippets/views.py
> +        # checklistのみの投稿として表示、判定させる
判定で事足りてる気もしますし
変更します
https://github.com/bob-g12/dayrepo-for-transportation/pull/56/commits/928c1c2066a2e9a40edcb9fcc4ea44bb7b16ae9c

2024-04-20 12:56 UTC, ittyi requested changes
コメントしました〜

2024-04-20 12:56 UTC, ittyi commented on dayrepo/snippets/templates/snippet_list.html
> +        <button type="submit">点検削除</button>
form タグ閉じてなくないです？
バグの元なので気をつけましょう〜

Auto Close Tagなどの  VScode 拡張機能はおすすめです
https://saishono.blog/setting-close-tag/

```suggestion
    <form method="post" action={% url 'db_delete' checklist.id 'checklist' %}>
        {% csrf_token %}
        <button type="submit">点検削除</button>
    </form>
```

2024-04-20 12:56 UTC, ittyi commented on dayrepo/snippets/templates/snippet_list.html
> +        <button type="submit">一括削除</button>
form タグ閉じてなくないです？
バグの元なので気をつけましょう〜

```suggestion
    <form method="post" action={% url 'db_delete' post.id 'snippet' %}>
        {% csrf_token %}
        <button type="submit">日報削除</button>
    </form>
    <form method="post" action={% url 'db_delete' post.id 'all' %}>
        {% csrf_token %}
        <button type="submit">一括削除</button>
    </form>
```

2024-04-20 12:56 UTC, ittyi commented on dayrepo/snippets/views.py
> +            process_object.delete()
以前 all_del のほうで指摘した内容です。
こう言うことがあるので、こういった完全に同じ共通処理は共通化したいんですよね〜🤔
```suggestion
        process_list = get_list_or_404(
            Process, snippet_id=target_id
        )
        for process in process_list:
            process.delete()
```

2024-04-20 12:56 UTC, ittyi commented on dayrepo/snippets/views.py
> +        )
インデント
```suggestion
        checklist = Checklist.objects.get(
            pk=target_id
        )
```

2024-04-20 12:56 UTC, ittyi commented on dayrepo/snippets/views.py
> +        checklist.delete()
処理の書き方を統一するなら、こうかなと思いました〜
```suggestion
        snippet = Snippet.objects.get(
            pk=target_id
        )
        checklist = Checklist.objects.get(
            pk=snippet.checklist_id.pk
        )
        dutiestrouble = DutiesTrouble.objects.get(
            snippet_id=target_id
        )
        process_list = get_list_or_404(
            Process, 
            snippet_id=target_id
        )
        
        snippet.delete()
        checklist.delete()
        dutiestrouble.delete()
        for process in process_list:
            process.delete()
```

2024-04-20 12:56 UTC, ittyi commented on dayrepo/snippets/views.py
> +        )
request.method != 'POST' に引っかかった場合 DbDeletePattern をインスタンスする意味がないのと、コメントなどを含めた一連の処理としては例外処理は別物なので、以下のようにした方がいいと思います。

```suggestion
def db_delete(request:HttpRequest, target_id:int, delete_type:str):
    if request.method != 'POST':
        raise ValueError(
            "本来入るはずのない処理に入りました。お手数ですが、システムにお問合せください。"
        )

    # 受け取ったdelete_typeから
    # 削除対象を判別し、実行クラスの処理を選択
    del_pattern = DbDeletePattern()
```

2024-04-20 13:53 UTC, ittyi approved these changes
LGTM〜

2024-04-20 13:53 UTC, ittyi commented on dayrepo/snippets/views.py
> +    return redirect(to="snippet_list")
謎の改行
```suggestion
    # 削除対象を判別し、実行クラスの処理を選択
    del_pattern = DbDeletePattern()
    if delete_type == "snippet":
        del_pattern.snippet_del(target_id)
    elif delete_type == "checklist":
        del_pattern.checklist_del(target_id)
    elif delete_type == "all":
        del_pattern.all_del(target_id)
    
    return redirect(to="snippet_list")
```

2024-04-20 13:53 UTC, merged