add:車両の管理ページを作成
bob-g12/dayrepo-for-transportation pull request #66
Opened 2024-04-27 05:44 UTC by bob-g12

2024-04-27 06:56 UTC, ittyi requested changes
コメントしました！

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/sub_views.py
> +from .models import Account, Car, Snippet, DutiesTrouble, Checklist, Process
使用していない model が多すぎると思います。余計な参照にも繋がるので、不使用なインポートはやめましょう〜

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/sub_views.py
新しくviewを作ることはいいと思います〜
subという命名はなにが書かれているのかが想像しづらいので、あまり良くないです。

業務用アプリであることを考えると、
マスター(master)
https://www.nttdata-value.co.jp/glossary/master-data
などは一般的な命名になります。

馴染がないかもしれませんが、業務アプリでは一般的なのでまだこのほうがいいと思います〜

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/sub_views.py
> +        # 記録してある投稿の全データを投稿時間を元にソートして表示
これ、本当ですか？
特にソートしていないような…🤔

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/sub_views.py
> +        # snippets は存在する時点で提出済みとみなす
車両の機能になぜsnippetsが関わってくるのでしょうか？

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/templates/vehicle_top_page.html
ファイルの命名変えたいです〜
まず、topページではありません。
1つのアプリ、サイトの中でtopページは1つであるべきだと思います。
車両内のトップ、という見方ができるかもわかりませんが、そのレベルに重要な画面ではないと思います〜


というのと、Pageの部分ですが、htmlの時点で基本的にPageを指しているので、ファイル名にはいれなくてもいいと思います〜

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/templates/vehicle_top_page.html
> +{% block page_title %}車両登録{% endblock %}
このページは登録する画面ではないと思います〜

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/templates/vehicle_top_page.html
> +{% block title %}車両登録{% endblock %}
ページのタイトルは1つでいいかと思います。
車両登録が重複しています〜

```suggestion
```

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/sub_views.py
> +        # トップページのhtmlへ日報データをテンプレートに渡す
これも嘘を書いていますね。
またどちらにせよいらないコメントかと思います〜
```suggestion
```

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/templates/vehicle_top_page.html
> +    <h2>車両リスト</h2>
日報のほうが「日報一覧」なので、一覧にするのかリストにするのかは合わせたほうがいいです〜

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/sub_views.py
> +    def get(self, request):
基本的に、今後は型ヒントをつけましょう〜

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/sub_views.py
> +    def get(self, request):
基本的に、今後は型ヒントをつけましょう〜

2024-04-27 06:56 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("top/vehicle/", sub_views.vehicle_list,name="vehicle_list"),
topではないです〜
というのと、他のリスト系の画面のパスと統一感のある命名にするべきかと思います。

2024-04-27 07:05 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +from .models import Account, Car, Snippet, DutiesTrouble, Checklist, Process
多すぎました
対応します。
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/e65ffe1746b76c07905d4fee114b1f1a79a81f8a

2024-04-27 07:07 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +        # 記録してある投稿の全データを投稿時間を元にソートして表示
コメント残ってました修正します

2024-04-27 07:07 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +        # snippets は存在する時点で提出済みとみなす
コメント残ってました修正します

2024-04-27 07:09 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_top_page.html
ではパスのtopはlistに変えます。
pageは消しておきます

2024-04-27 07:10 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +        # トップページのhtmlへ日報データをテンプレートに渡す
コメント削除しておきます

2024-04-27 07:11 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_top_page.html
> +{% block page_title %}車両登録{% endblock %}
削除しておきます

2024-04-27 07:11 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_top_page.html
> +    <h2>車両リスト</h2>
対応します。

2024-04-27 07:12 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("top/vehicle/", sub_views.vehicle_list,name="vehicle_list"),
listに変えます

2024-04-27 07:12 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +        # トップページのhtmlへ日報データをテンプレートに渡す
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/f26116688970e0f311793e2fc2f9803a91cdc011

2024-04-27 07:13 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +        # 記録してある投稿の全データを投稿時間を元にソートして表示
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/f26116688970e0f311793e2fc2f9803a91cdc011

2024-04-27 07:18 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
viewsをどう分けるかで命名も変えようかと思いますが、
今のところ車両と社員の処理を同じにしようと思っています。
それでよい場合、またはほかにも処理を合わせた方がいい場合、
それに合わせた命名にしたいと考えてます。

2024-04-27 07:18 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +        # 記録してある投稿の全データを投稿時間を元にソートして表示
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/f26116688970e0f311793e2fc2f9803a91cdc011

2024-04-27 07:18 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +        # snippets は存在する時点で提出済みとみなす
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/f26116688970e0f311793e2fc2f9803a91cdc011

2024-04-27 07:30 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_top_page.html
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/25e798c4b60af1a7ff8fa93688c133cd8fca17f8

2024-04-27 07:31 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_top_page.html
> +{% block page_title %}車両登録{% endblock %}
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/03f0add227db12d510bf683907fdb657ff002c67

2024-04-27 07:32 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +        # トップページのhtmlへ日報データをテンプレートに渡す
削除しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/f26116688970e0f311793e2fc2f9803a91cdc011

2024-04-27 07:32 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_top_page.html
> +    <h2>車両リスト</h2>
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/03f0add227db12d510bf683907fdb657ff002c67

2024-04-27 07:33 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +    def get(self, request):
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/bed8fa6f7ff9c68873b333025048a92ddbd642c7

2024-04-27 07:34 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("top/vehicle/", sub_views.vehicle_list,name="vehicle_list"),
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/25e798c4b60af1a7ff8fa93688c133cd8fca17f8

2024-04-27 07:40 UTC, ittyi commented on dayrepo/snippets/sub_views.py
> +from .models import Account, Car, Snippet, DutiesTrouble, Checklist, Process
Account も消そう。
今時点で使っていないだけで後で使うとしても、このPRの差分として入れるのは好ましくない。

と言うのと、実際の業務では明日やることが変わることもあるので、習慣としてしようしていない変数や宣言は消す癖もつけよう〜
TODOコメントを残す、とかならわかるんだけどね。今回のはこれもいらないカナ〜

2024-04-27 07:43 UTC, ittyi commented on dayrepo/snippets/sub_views.py
・日報の登録や編集などはこのアプリのコアになる機能、かつ動作を表す機能
・社員や車両などはあくまでも企業に必要な情報として残す情報。それを他の機能で利活用するもの。
といった棲み分けができるので、分け方はそれでいいと私も思います〜。

そういった意味でも、マスターという命名がかなり適任ではありますね。

2024-04-27 07:48 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
変更しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/0b5ef6cc1782f2942e25485489c8b71858a26282

2024-04-27 07:53 UTC, bob-g12 commented on dayrepo/snippets/sub_views.py
> +from .models import Account, Car, Snippet, DutiesTrouble, Checklist, Process
削除しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/6ab47409a536b1d0a55bb542bb9fa1f50aefcb66

2024-04-27 08:01 UTC, ittyi requested changes
コメントしました〜

2024-04-27 08:01 UTC, ittyi commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
[Q]
ぱっと調べてもよくわからなかったので質問なんだが、`{% block page_title %}`  と `{% block title %}`の違いってなんなんだ？

他の画面も全て二つあることに気づいた。意味があった説
https://github.com/bob-g12/dayrepo-for-transportation/blob/2adba11542ffe48934f76a2747be234639914e94/dayrepo/snippets/templates/snippet_post.html#L2

2024-04-27 08:17 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
画面上のタイトルと、タブのタイトルでそれぞれ設定してたはず
まだデザインでしっかり設定してないので後回しのつもりでした。
tub_titleとかでよさそうですね

2024-04-27 08:23 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +        cars = Car.objects.all()
メーター数の多い順に変えました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/ac369eca80b7bde12cba6d5a44e84ac8b1567d41

2024-04-27 08:33 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +            {"vehicles": cars},
car で統一しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/a3a526dec6c06e231dd21bb69196409afc1f7124

2024-04-27 08:45 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
[こちら](https://github.com/bob-g12/dayrepo-for-transportation/issues/64)のコード整理で行う想定です。

2024-04-27 14:11 UTC, ittyi commented on dayrepo/snippets/master_views.py
では、忘れないように具体的にどう修正するのかまで明記しましょう〜

2024-04-27 14:13 UTC, ittyi commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
デザインとかではなく、セマンティクスやアクセシビリティの問題なので、今時点でちゃんとやった方がいいですね。
と言うのと、元々の{% block page_title %}と {% block title %}に意味があったのであれば、消す必要がないので元に戻しておいて下さい〜

2024-04-27 14:19 UTC, ittyi reviewed
最後です〜

2024-04-27 14:19 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("list/car/", master_views.car_list,name="car_list"),
細かいんですが、これだとパスが
localhost:0000/snippets/list/car になることに気づきました。
snippetsのリストのようになってしまうので、適切なパスではないかもです。

いっそ
localhost:0000/snippets/cars の複数形でいいじゃないかなと思ったんだがどうだろう。多分正しくやるならそもそもsnippetsの配下じゃないんだろうなぁ。。

2024-04-27 14:19 UTC, ittyi commented on dayrepo/snippets/templates/car_list.html
> +    <div id="car">
id名が抽象的すぎるので、car の何を表現しているのがこのdiv タグなのかまで命名できるとなお良いと思いました。

2024-04-28 00:13 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
以前作成したこのissueで計画する予定です。
https://github.com/bob-g12/dayrepo-for-transportation/issues/63

2024-04-28 01:29 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
{% block %}タグ要らなかったので削除しました。
他のhtmlファイルの修正は別のPRで対応します。(PRの対象ファイルが増えすぎるため)

2024-04-28 01:31 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("list/car/", master_views.car_list,name="car_list"),
ではcarsにしておきます
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/291f5daf51e2c20a0cc0560e13f34f9e478d9379

2024-04-28 01:34 UTC, bob-g12 commented on dayrepo/snippets/templates/car_list.html
> +    <div id="car">
car_listに変更しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/3fffb67877f386c5d524262f21e15531fef0b362

2024-04-28 01:46 UTC, ittyi commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
なぜいらなかったんですか？
そこの理由が気になります〜

ここの会話までは必要そうでしたが、、
https://github.com/bob-g12/dayrepo-for-transportation/pull/66#discussion_r1581756784

2024-04-28 01:54 UTC, ittyi commented on dayrepo/snippets/templates/car_list.html
> +    <div id="car">
この div タグって  {% for car in cars %} で生成される一つ一つのrecord、item、block、content、とかに当たるので、list にしてしまうと車両一覧の中に大量のなんかのリストができてしまうような命名になっていて違和感がある。

細かいけど命名は大切なので〜

2024-04-28 02:04 UTC, ittyi reviewed
コメントしました〜

2024-04-28 02:06 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
タブやタイトルを置き換えるつもりがないため通常のtitleタグや見出しタグで十分と判断しました

2024-04-28 02:28 UTC, bob-g12 commented on dayrepo/snippets/templates/car_list.html
> +<title>車両管理画面</title>
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/1520f1cdd5834bdc3db1feb57e675f49ac0ba8a8

2024-04-28 02:37 UTC, bob-g12 commented on dayrepo/snippets/templates/car_list.html
> +    <div id="car">
car_blockにしておきました
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/3fffb67877f386c5d524262f21e15531fef0b362

2024-04-28 03:03 UTC, ittyi commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
置き換えると言うのは、何と置き換えるんですか？
※{% block %}タグの役割がまだイマイチよくわかっていない民

2024-04-28 03:36 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
領域を確保して、別のテンプレートに置き換えることができるみたいです。
https://wonderwall.hatenablog.com/entry/2018/03/13/213000

2024-04-28 08:29 UTC, ittyi commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
その使用用途であれば、必要は必要だけど今やりたくないだけだと思うので、headタグもtitleタグも今は入れない。でいいんじゃないかなーと思った🤔どう？

2024-04-28 08:38 UTC, bob-g12 commented on dayrepo/snippets/templates/vehicle_list.html
> +{% block page_title %}車両一覧{% endblock %}
了解です。
対応しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/66/commits/0025d173fda16ec0603ce7d1693f3da70b3f5d0c

2024-04-28 08:46 UTC, ittyi approved these changes
LGTM!

2024-04-28 08:46 UTC, merged