test
bob-g12/dayrepo-for-transportation pull request #70
Opened 2024-04-29 06:50 UTC by bob-g12

2024-04-29 08:28 UTC, bob-g12 commented
新規登録画面
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/721f0ee6-171f-4244-ad0f-a639969da00b)

2024-04-29 09:07 UTC, bob-g12 commented
追加が可能になりました
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/bf37cd09-94ca-4825-bca1-0ed0e773f7d2)

![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/6bdb6705-801c-4ea0-ace2-cee83f50a3f6)

2024-04-29 16:26 UTC, ittyi requested changes
コメントしました〜

2024-04-29 16:26 UTC, ittyi commented on dayrepo/snippets/templates/car_add.html
> +<link rel="stylesheet" href='{% static "css/style.css" %}'>
これは基本的にheadタグの子要素なので、使用する場合は　headタグで囲いましょう。
https://html-coding.co.jp/annex/dictionary/html/link/

また、これ系は以前もあったので、タグがなんの子要素なのかは確認したほうがいいと思います〜

2024-04-29 16:26 UTC, ittyi commented on dayrepo/snippets/static/css/style.css
今回のこのCSSは　車両系のフォームに特化している指定が集まっているかと思いますので、もっと限定的なファイル名にするべきかと思います。

2024-04-29 16:26 UTC, ittyi commented on dayrepo/snippets/templates/car_add.html
> +        <input type="text" name="vehicle_number_place" class="vehicle_number_place" maxlength="10" required="" id="id_vehicle_number" placeholder=札幌>
既にidを振っている中で、あえてクラスも用意している意図などはありますか？
クラス名のメリットは一意な命名ではなく他のタグと重複した命名が可能で、いっぺんにCSSなどを当てられることにあったりするので、 IDで十分であれば IDだけでいいと思います。
※他のタグも同様

また、　実はname属性は非推奨なので、今後CSSなどを記載していくようであれば、基本的には IDだけで十分です。
https://oopsoop.com/usage-of-name-id-class/

一緒に指定したい需要（例えば、一覧画面のデザインは各画面で統一したい、ボタンも同じデザインにしたい、など）が出てきたらクラスを使用する。といった流れがオーソドックスです。

JSのconstみたいなものですね。基本的には縛りがきつい方を優先的に使いましょう。

2024-04-29 16:26 UTC, ittyi commented on dayrepo/snippets/templates/car_add.html
> +        <input type="number" name="vehicle_number_type" class="vehicle_number_type" maxlength="3" required="" id="id_vehicle_number" placeholder=100>
id_vehicle_numberという、 ID名が他のタグとかぶっているのはよろしくありません。 セマンティクスとしても、支援技術でエラーが出ないようにするためにも重要です。

https://waic.jp/translations/WCAG-TECHS/H93.html
> この達成方法の目的は、異なる要素に同一の id 属性値があることによって、支援技術がコンテンツを解析しようとする際に問題が生じるエラーを回避することである。このエラーは、ウェブページに重複した id 属性値がないことを確認することによって回避できる。

2024-04-29 16:26 UTC, ittyi commented on dayrepo/snippets/templates/car_add.html
> +        <input type="text" name="vehicle_number_use" class="vehicle_number_use" maxlength="1" required="" id="id_vehicle_number" placeholder=あ>
required 属性は、基本的に何かを代入するような属性じゃないのと、こう書いてしまうと必須項目になっていないのではないでしょうか？動作確認はしてみましたか？（単純にやったことないので気になる
https://developer.mozilla.org/ja/docs/Web/HTML/Attributes/required
```suggestion
        <input type="text" name="vehicle_number_use" class="vehicle_number_use" maxlength="1" required　id="id_vehicle_number" placeholder=あ>
```
※他のタグも同様です

2024-04-29 16:26 UTC, ittyi commented on dayrepo/snippets/templates/car_add.html
> +    <button name="btn_car_post" type="submit" class="car_post_button">
id でいいかなと思います〜
上でも指摘しましたが、name属性は基本的に不要です。
CSSをつけ始めるのであればちゃんとやっていきましょう〜

また、他のページはbutton  で終わっていることが多いですが、ここだけpostとつけたのは意図がありますか？（あればOKです（と言いつつ、postをつけるならcar_postでよくないとも思いました
https://github.com/bob-g12/dayrepo-for-transportation/blob/main/dayrepo/snippets/templates/snippet_post.html
```suggestion
    <button type="submit" id="car_post">
```

2024-04-29 16:26 UTC, ittyi commented on dayrepo/snippets/urls.py
> +    path("add/cars/", master_views.car_add,name="car_add"),
パスが
snippets/add/cars
となっており、　snippetsをaddしていそうなのと、複数のcarが関わるような命名になっています。

他の実装に合わせるならnewになるのではないでしょうか。
```suggestion
    path("car/new/", master_views.car_add,name="car_add"),
```

2024-04-30 09:35 UTC, bob-g12 commented on dayrepo/snippets/urls.py
> +    path("add/cars/", master_views.car_add,name="car_add"),
こちらで対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/1ee91ed6317131b7b4407d16c0d29ceb89785af0

2024-04-30 09:39 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +class CarAddView(View):
こちらで対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/1ee91ed6317131b7b4407d16c0d29ceb89785af0

2024-04-30 09:40 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +            "car_add.html",
今回のcarのhtmlをあわせてcar_post.htmlにしました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/d0cd7dd203479b5d9430d6538b44e51d59653efe

2024-04-30 10:08 UTC, bob-g12 commented on dayrepo/snippets/static/css/style.css
変更しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/e980621a91d44c214a07956a4faa409dab1b48ed

2024-04-30 13:11 UTC, bob-g12 commented on dayrepo/snippets/templates/car_add.html
> +<link rel="stylesheet" href='{% static "css/style.css" %}'>
対応しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/19e0a831132bcfb206840c349a9e30309e54c479

2024-04-30 13:25 UTC, bob-g12 commented on dayrepo/snippets/templates/car_add.html
> +        <input type="text" name="vehicle_number_use" class="vehicle_number_use" maxlength="1" required="" id="id_vehicle_number" placeholder=あ>
必須項目として機能しています。
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/1fd9d54e-8edd-4776-a79d-3bae522a10a9)

2024-05-01 12:29 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +        )
カラムの変更により、大きな統合はなくなりました。

2024-05-01 12:32 UTC, bob-g12 commented on dayrepo/snippets/static/css/style.css
> +input.vehicle_number_place,
idで指定しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/5caae8e7fe985e04fe110e79e4553c7c06c4da96

2024-05-01 12:40 UTC, bob-g12 commented on dayrepo/snippets/static/css/style.css
> +    display: inline-block;
displayは inlineに変更しました。

2024-05-01 12:42 UTC, bob-g12 commented on dayrepo/snippets/templates/car_add.html
> +        <input type="text" name="vehicle_number_place" class="vehicle_number_place" maxlength="10" required="" id="id_vehicle_number" placeholder=札幌>
classだった箇所はidに変更しました。

2024-05-01 12:43 UTC, bob-g12 commented on dayrepo/snippets/templates/car_add.html
> +        <input type="number" name="vehicle_number_type" class="vehicle_number_type" maxlength="3" required="" id="id_vehicle_number" placeholder=100>
id名変更しました
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/5caae8e7fe985e04fe110e79e4553c7c06c4da96

2024-05-01 12:44 UTC, bob-g12 commented on dayrepo/snippets/templates/car_add.html
> +        <input type="text" name="vehicle_number_use" class="vehicle_number_use" maxlength="1" required="" id="id_vehicle_number" placeholder=あ>
=""があっても機能しましたが、削除しておきました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/663573ff0ba6b20e5e552f14e5e66beb55b76bd6

2024-05-03 03:10 UTC, bob-g12 commented on dayrepo/snippets/static/css/style.css
> +    display: inline-block;
Flexboxを使用して対応しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/75c62788358d8dd8de33c5a753b3dcb5f40d0fd1

2024-05-03 12:33 UTC, ittyi reviewed
コメントしました〜

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/master_views.py
> +            + "-" + req.get("serial_number_end")
識別番号ですが、ハイフンで繋げる意味はあるかな？単なる4桁の番号でいいような🤔

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/master_views.py
> +        if req.get("serial_number_top") != "":
topは入力必須ではない感じです？
というのと、topは確認するけどendはみないのでしょうか？

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/master_views.py
> +            number = req.get("serial_number_end")
[Q]
このケースだと、2桁の番号になってしまうことはない？

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/migrations/0001_initial.py
> +                ('serial_number', models.CharField(max_length=5, verbose_name='車両_一連指定番号')),
5桁…？
ハイフンも入れる感じです？

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/models.py
>      # TODO: バリデーションの実装 issue -> https://github.com/bob-g12/dayrepo-for-transportation/issues/15
このissue、たぶんわいがメモってたやつなんだが今回で解決したので消させてくれたも
```suggestion
```

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/templates/car_post.html
> +    <div id=vehicle_number>
文字列です〜
```suggestion
    <div id="vehicle_number">
```

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/templates/car_post.html
> +        <input type="text"  maxlength="10" id="place_name" name="place_name" placeholder="札幌" required>
特に理由がなければ、nameは基本的に不要です
```suggestion
        <input type="text"  maxlength="10" id="place_name" placeholder="札幌" required>
```

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/templates/car_post.html
> +        <input type="text"  maxlength="10" id="place_name" name="place_name" placeholder="札幌" required>
この項目は選択ボックスにできるかと思いますが、今回はしないですか？
入力が限定できるのでやれたらいいな機能ではあります。
※一旦 issue 化だけするとかもアリ

というのと、そうしない場合、maxlength="10"の部分がかなり危険です。
というのも、DBの制約上大きくしておくのは構わないのですが、余分な空白や存在しない地名などが入力できてしまうリスクがあります。というか、ほぼ入力されてしまうUIになっていると思います〜

そのため、このまま行く場合は

- 最低でも最大文字数を四桁にする: https://trafficnews.jp/post/95976
- views.py  or JS or 正規表現などで、余分な文字が入っていないか（特に空白、ハイフン、アンダーバー、などの記号系）をチェックする機構

などが必要だと思います。

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/templates/car_post.html
> +        <input type="text" maxlength="1" id="kana" name="kana" placeholder="あ" required>
ここも選択ボックスにはしないですか？
というのと、しない場合は views.py or JS  or 正規表現などで別途バリデーション処理が必要かと思います〜

2024-05-03 12:33 UTC, ittyi commented on dayrepo/snippets/templates/car_post.html
> +        <input type="number" id="now_mileage" name="now_mileage" placeholder="車両の初期メーター値km" required>
特に理由がなければ、nameは基本的に不要です
```suggestion
        <input type="number" maxlength="3" id="class_number" placeholder="100" required>
        <input type="text" maxlength="1" id="kana" placeholder="あ" required>
        <input type="number" maxlength="2" id="serial_number_top" placeholder="88">
        -
        <input type="number" maxlength="2" id="serial_number_end" placeholder="88" required>
    </div>
    </p>
    <p>
        <label for="id_now_mileage">走行距離:</label>
        <input type="number" id="now_mileage" placeholder="車両の初期メーター値km" required>    
```

2024-05-03 13:10 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +            + "-" + req.get("serial_number_end")
表示する際に間にハイフンが欲しいので、一つのカラムとして保存するにあたり、表示変更を毎度行うよりも、別々で受け付けた初めのうちにハイフンを入れておいた方が分かりやすく、早いと思いました。

2024-05-03 13:12 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +        if req.get("serial_number_top") != "":
識別番号を4桁で考えていましたが、1桁や２桁も可能らしいので、未入力も許容したうえで、３桁目以降の入力がない場合はハイフンや統合をしないで下２桁までを登録する方式にしました。

2024-05-03 13:13 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +            number = req.get("serial_number_end")
上と同じく、１桁まであり得るそうなのでそちらに対応しました。

2024-05-03 13:40 UTC, ittyi commented on dayrepo/snippets/master_views.py
> +            + "-" + req.get("serial_number_end")
なるほどーと思いつつ調べましたが、
https://www.ms-ins.com/labo/higoro/article/049.html#:~:text=%E3%81%84%E3%82%8F%E3%82%8C%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82-,%E4%B8%80%E9%80%A3%E6%8C%87%E5%AE%9A%E7%95%AA%E5%8F%B7,%E7%94%B3%E3%81%97%E8%BE%BC%E3%82%80%E3%81%93%E3%81%A8%E3%82%82%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82

https://kuruma-news.jp/post/390910
> よく見てみると4桁の場合には真ん中にハイフンが使われていますが、2桁や3桁ではハイフンは使われず、代わりになかぐろが使われています。
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/62760395/e620dda4-6aa8-446a-8c31-ed39e1b5d04e)

基本的に空白には点(・)が入るようです。何桁であろうと・埋めするようなので、バリデーションついでに・埋めをすれば、1桁、2桁だけの文字列というのはなくせるかと思いました。

また、やっぱり調べても一連識別番号自体は単なる「4桁の」番号というソースしか見当たらないないのと**4桁未満の場合はハイフンが入らない**ようです。

データとしては、少なくともDB上では4桁の数字だけにするのが正しい形だと思います。
それでも分けたい、もしくは表示上はハイフンを入れたい、ということであれば、そこもカラムを分けて対応するべきだと思います〜

2024-05-03 13:40 UTC, ittyi commented on dayrepo/snippets/master_views.py
> +        if req.get("serial_number_top") != "":
内容似ていたのでこちらでやり取りします〜
https://github.com/bob-g12/dayrepo-for-transportation/pull/70#discussion_r1589220217

2024-05-03 13:40 UTC, ittyi commented on dayrepo/snippets/master_views.py
> +            number = req.get("serial_number_end")
内容似ていたのでこちらでやり取りします〜
https://github.com/bob-g12/dayrepo-for-transportation/pull/70#discussion_r1589220217

2024-05-03 14:34 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +            + "-" + req.get("serial_number_end")
正式な書類においてハイフンやなかぐろは必要ないのか、
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/80a893a1-f4da-4edc-a714-8f3f312b1eaa)
じゃあ、要らないですか、
余分なハイフンやなかぐろを入力されないためにもフォームは分けますが、区切りはなくします。
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/ebb6531066daab6ce048184ebaf721584b4d2721

2024-05-04 05:20 UTC, ittyi reviewed
コメントしました〜

2024-05-04 05:20 UTC, ittyi commented on dayrepo/snippets/templates/car_post.html
> +    </p>
<div>要素はコンテンツの論理的なグループ化やスタイルの適用のために使用される要素なので、「段落」ではないためPタグで囲われるのは適切ではありません〜

##### コンテンツモデルについて
また、HTMLにはコンテンツモデルという概念があります。（昔はブロックレベル、インラインレベルという要素でした。）
https://creatorquest.jp/reference/html/categories/
> 「〇〇要素の中には、△△要素が配置できる」といった、各要素ごとに中に配置できる要素を定義した配置ルール

https://creatorquest.jp/reference/html/element/p/
Pタグはフローコンテンツにあたるため、その子孫タグとしてはフレージングコンテンツのみです。
https://creatorquest.jp/reference/html/categories/#phrasing-content

2024-05-04 05:20 UTC, ittyi commented on dayrepo/snippets/templates/car_post.html
> +        <input type="number" id="now_mileage" name="now_mileage" placeholder="車両の初期メーター値km" required>
for 属性の用途としては、 input タグとの紐付けを明示的にすることにあるため、 id と同じにする必要があります。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/label
> for の値は <input> 要素の id と同じにします。


```suggestion
        <label for="now_mileage">走行距離:</label>
        <input type="number" id="now_mileage" name="now_mileage" placeholder="車両の初期メーター値km" required>    
```

2024-05-04 05:20 UTC, ittyi commented on dayrepo/snippets/templates/car_post.html
> +        <label>車両番号:</label>
明示的にどのinputタグに紐づいているのかを判別させるため、このlabelタグの中に全てのinput タグを入れてしまいましょう

https://developer.mozilla.org/ja/docs/Web/HTML/Element/label
> <label> 要素と <input> 要素を明示的に関連付けるには、最初に id 属性を <input> 要素に追加します。次に、for 属性を <label> 要素に追加します。for の値は <input> 要素の id と同じにします。
> 
> 他の方法として、 <input> を直接 <label> の内側に入れることができますが、この場合は関連付けが明確なので、 for および id 属性は必要ありません。

2024-05-04 05:20 UTC, ittyi commented on dayrepo/snippets/master_views.py
> +            number = req.get("serial_number_end")
HTMLを確認しましたが、この場合serial_number_topは必須項目ではない　＝ 入力されない場合は単なる空白になる
はずなので、そもそもこの if 文はいらないかなと思いました。
```suggestion
        number = int(
            str(req.get("serial_number_top"))
            + str(req.get("serial_number_end"))
        )
```

また個人的には、数字で受け取るのであればserial_number_topとserial_number_endにフォームの分ける必要性もないような気がしています。
特に、serial_number_top にserial_number_endの値を入力されてしまうリスクがあるためです。まぁ、一旦そこらへんの判断は任せます〜

2024-05-04 06:22 UTC, bob-g12 commented on dayrepo/snippets/master_views.py
> +            number = req.get("serial_number_end")
対応しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/9ccbcc22a5ca68a0cd1e724b0c97e210d3f9f122
システム側でハイフンの考慮がされていることは伝わってほしいのでフォームは分けたいですね。

2024-05-04 06:26 UTC, bob-g12 commented on dayrepo/snippets/templates/car_post.html
> +        <label>車両番号:</label>
対応しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/cc63d386f1b105923732c7f2cee3bf3e2804cd74

2024-05-04 06:26 UTC, bob-g12 commented on dayrepo/snippets/templates/car_post.html
> +    </p>
対応しました。
https://github.com/bob-g12/dayrepo-for-transportation/pull/70/commits/179eabf6efe4b4a5a7fe39ce492ea8d29f0d68fb

2024-05-04 08:06 UTC, ittyi approved these changes
LGTM~

2024-05-04 08:06 UTC, merged